Knuth_Morris_Pratt_Algorithm/KMP.cpp, Z_Algorithm/Z_Algorithm.cpp
When we allocate an array using the new …[…] syntax, we should deallocate it using delete[]. In these cases, we needed to change delete to delete[]. If we use the wrong form of delete to match our allocation with new, we have undefined behavior. REF: http://stackoverflow.com/a/21500476
Found by https://github.com/bryongloden/cppcheck
=> fix error with allocation and deallocation mismatch

Optimal_Binary_Search_Tree/Optimal_Binary_Search_Tree.c
=> Optimal_Binary_Search_Tree

Harmonic_Progression/Harmonic_Progression.c, Harmonic_Progression/Harmonic_Progression.cpp, Harmonic_Progression/Harmonic_Progression.go, Harmonic_Progression/Harmonic_Progression.java, Harmonic_Progression/Harmonic_Progression.py
Fixes #1223 
- Nth term of Harmonic progression
- C
- C++
- Java
- Python
- Go
- Harmonic_Progression.c
- Harmonic_Progression.cpp
- Harmonic_Progression.java
- Harmonic_Progression.py
- Harmonic_Progression.go
=> Nth term of Harmonic Progression

Pythagorean_Quadruples/Pythagorean_Quadruples.c, Pythagorean_Quadruples/Pythagorean_Quadruples.cpp, Pythagorean_Quadruples/Pythagorean_Quadruples.go, Pythagorean_Quadruples/Pythagorean_Quadruples.java, Pythagorean_Quadruples/Pythagorean_Quadruples.py
Fixes #1329 
- Added Pythagorean Quadruples in 5 languages
- C
- C++
- Java
- Go
- Python
- Pythagorean_Quadruples.c
- Pythagorean_Quadruples.cpp
- Pythagorean_Quadruples.py
- Pythagorean_Quadruples.go
- Pythagorean_Quadruples.java
=> Added pythagorean quadruples

Partial_Dearrangements/Partial_Dearrangements.c, Partial_Dearrangements/Partial_Dearrangements.cpp, Partial_Dearrangements/Partial_Dearrangements.go, Partial_Dearrangements/Partial_Dearrangements.java, Partial_Dearrangements/Partial_Dearrangements.py
Fixes #1399 
- Added Partial Dearrangements Implementation
- C
- C++
- Java
- Python
- Go
- Partial_Dearrangements.c
- Partial_Dearrangements.cpp
- Partial_Dearrangements.go
- Partial_Dearrangements.java
- Partial_Dearrangements.py
=> Added Partial Dearrangements

Aho-Corasick/Aho-Corasick.cpp, Aho-Corasick/Aho-Corasick.java
Fixes #624 
- Aho-Corasick Algorithm
- C++
- Aho-Corasick c++ code
=> Aho corasick

Minimum_Cost_Path/Minimum_Cost_Path.c, Minimum_Cost_Path/Minimum_Cost_Path.cpp, Minimum_Cost_Path/Minimum_Cost_Path.java, Minimum_Cost_Path/Minimum_Cost_Path.py
Fixes #1396 
- added Min Cost Path in 2d-Array  
- C
- C++
- java
- python
- Minimum_Cost_Path.c 
- Minimum_Cost_Path.cpp
- Minimum_Cost_Path.java 
- Minimum_Cost_Path.py
=> Added Minimum Cost Path

Doubly_Linked_List/Doubly_linked_list.rb, Josephus_Problem/Josephus_Problem.java
Fixes #1407 
- Java code for Josephus Problem
- Java
- Josephus_Problem.java
Thanks!
=> Java implementation for Josephus Problem added.

Palindromic_Array/Palindromic_Array.c, Palindromic_Array/Palindromic_Array.cpp, Palindromic_Array/Palindromic_Array.go, Palindromic_Array/Palindromic_Array.java, Palindromic_Array/Palindromic_Array.py
Fixes #1434 
- Added implementation to check whether an array is palindromic or not 
- C
- C++
- Java
- Python
- Go
- Palindromic_Array.c
- Palindromic_Array.cpp
- Palindromic_Array.java
- Palindromic_Array.py
- Palindromic_Array.go
=> Check whether an array is Palindromic or not

Fibonacci_Number/README.md
Fixes #
- Adding README file for Fibonacci_Number
- 
- English
- 
- README.md
- 
Thanks!
=> Fixes #1571 [Added README File]

Coin_Change/Coin_Change.js
Fixes #2081 
-  Implementation of Coin Change Problem in JavaScript since no solution was present.
- JavaScript
- Added a file Coin_Change.js in Coin_Change folder
Thanks!
=> Coin Change Problem solution in JS

Fibonacci_Number/Fibonacci_Number.js
Fixes #1609 
- Created JS implementation of the said problem.
- JavaScript
- Fibonacci_Number.js
Thanks!
=> Fibonacci number Implementation in JS. Closes #1609

Fermat_Little_Theorem/Fermat_Little_Theorem.java
Fixes #2024 
- Added java implementation of Fermat_Little_Theorem
- 
- java
- 
- Fermat_Little_Theorem.java
- 
Thanks!
=> issue 2024 Fermat_Little_Theorem java

Binary_Insertion_Sort/Binary_Insertion_Sort.py
=> Implementation of Binary Insertion Sort in Python

Hamiltonian_Cycle/Hamiltonian_Cycle.cpp
Fixes #1812 
- Implementation of Hamiltonian Cycle
- C++
- Hamiltonian_Cycle.cpp
@jainaman224  @SakshiShreya 
Thanks!
=> Added Hamiltonian_Cycle.cpp

Spiral_Array/Spiral_Array.cpp
Fixes #1607 
- Implemented the Spiral Matrix in C++
- 
- C++
- 
- Spiral_Array/Spiral_Array.cpp
- 
Thanks!
=> Spiral Array C++

Palindrome/palindrome_string.py, Palindrome/pallindrome_string.py
Issue no #1718
- Added a new code
- 
- Python
- 
- palindrome_string.py
- 
Thanks!
=> check whether a string is palindrome

Bisection_Method/Bisection_Method.cpp
Fixes #1914
-Added a  C++ implementation of bisection method
- C++
- Bisection_Method.cpp
Thanks!
=> Added Bisection_Method.cpp

Circular_Queue/Circular_Queue.java
Fixes #1824 
- Circular Queue operations (Insert, Delete, Display)
- Java
- Circular_Queue.java
Thanks!
=> Circular Queue in JAVA

Shell_Sort/Shell_Sort.cs
Fixes #2156 
- Added a file ShellSort.cs
- 
- C#
- 
- shell_sort.cs
- 
Thanks!
=> Added shell sort.cs

Minesweeper/minesweeper.cpp
Fixes #1598 
- Added implementation of Minesweeper in C++
- 
- C++
- 
- Minesweeper/minesweeper.cpp
- 
Thanks!
=> Added minesweeper implementation in C++

Longest_Increasing_Subsequence/LIS.go
Fixes #2253
- LIS code in Golang
- 
- Go
- 
- LIS.go
- 
Thanks!
=> Added Longest Increasing Subsequence code in Go

Max_Circular_SubArray_Sum/max_circular_subArray_sum.c, Max_Circular_SubArray_Sum/max_circular_subarray_sum.cpp
Fixes #1728
- 
- 
- C
- C++
- max_circular_subArray_sum.c 
- max_circular_subarray_sum.cpp 
Thanks!
=> Max_circular_sum_added 2-C/C++

Palindrome/palindrome_no.java
Fixes #1718 
- Added a new code
- 
- Java
- 
- palindrome_no.java
- 
Thanks!
=> check palindrome in a number in Java

kosaraju_algorithm/kosaraju_algorithm.cpp
Fixes #2246 
- add kosaraju algorithm in cpp
- 
- c++
- 
- kosaraju_algorithm.cpp
- 
Thanks!
=> add kosaraju algorithm in cpp

Minimum_Absolute_Difference_In_Array/Minimum_Absolute_Difference_In_Array.c, Minimum_Absolute_Difference_In_Array/Minimum_Absolute_Difference_In_Array.cpp
Fixes #1776 
Checklist:
-  [x] 4 space indentation.
Changes proposed in this pull request:
-  Added implementation of the problem in C and C++. 
Languages Used: 
- C 
- C++
Files Added:
- MinAbsolute_Diff.c
- MinAbsolute_Diff.cpp
=> Added Minimum Absolute Difference in Array problem [C and C++ implementation]

Count_Inversion/Count_Inversion.cpp
=> Count_Inversion.cpp

Tree_Inorder_Traversal/Inorder_Traversal.kt
Fixes #2552
- Add Inorder Traversal in Kotlin.
- Kotlin
- Inorder_Traversal.kt 
Thanks!
=> Add Inorder Traversal in Kotlin

Ford_Fulkerson_Method/README.md
issue no. is #2477 Ford Fulkerson Method
Fixes #2477
- readme of Ford Fulkerson Method is added
- English
- README.md
Thanks!
=> Adding the readme for Ford Fulkerson Method

Tree_Inorder_Traversal/Tree_Inorder_Traversal.cs
Fixes #2552 
- Tree Inorder Traversal In C#
- Menu Driven & Dynamic
- C#
- 
- Tree_Inorder_Traversal.cs
- 
Thanks!
=> Tree Inorder Traversal In C#

Z_Algorithm/README.md
Fixes #2478 
- readme for #2478  Z algorithm
Thanks!
=> Readme for Z algorithm

Longest_Increasing_Subsequence/LIS.php
Fixes #2253 
- 
- 
- PHP
- LIS.php 
Thanks!
=> Adding PHP implementation for LIS (Issue #2253)

Tree_Levelorder_Traversal/Tree_Levelorder_Traversal.js
Fixes #2553 
- JavaScript - JS 
- Tree_Levelorder_Traversal.js
Thanks!
=> Tree- level order traversal in JS 

Tree_Levelorder_Traversal/Tree_Levelorder_Traversal.kt
Fixes #2553 
- Added Code for level order traversal in kotlin
- Kotlin
- Tree_Levelorder_Traversal.kt
Thanks!
=> Add Level Order Traversal in Kotlin

Longest_Common_Subsequence/Longest_Common_Subsequence.rb
Fixes #2252 
- Added implementation of Longest Common Subsequence in Ruby
- Ruby
- Added Longest_Common_Subsequence.rb under Longeest_Common_Subsequence folder
Thanks!
=> Added LCS implementation in Ruby (#2252)

Ternary_Search/Ternary_Search.kt
#2176
Fixes #2745 
- Added a new file Ternary_Search.kt
- 
- Kotlin
- 
- Ternary_Search.kt
- 
Thanks!
=> Created Ternary_Search.kt

Karatsuba_Algorithm/Karatsuba_Algorithm.go
Fixes #2248 
- Karatsuba Algorithm In GO
- Dynamic User Input Taken
- GO
- 
- Karatsuba_Algorithm.go
- 
Thanks!
=> Karatsuba Algorithm In GO

Boyer_Moore_Algorithm/Boyer_Moore.kt
Fixes #2480 
- Added Boyer_Moore_Algorithm in Kotlin
- Kotlin
- Boyer_Moore.kt
Thanks!
=> Added Boyer_Moore_Algorithm in Kotlin

Postman_Sort/Postman_Sort.js
Fixes #2251 
- Added Postman Sort Implementation in JavaScript
- JavaScript
- Postman_Sort.js
Thanks!
=> Added Postman Sort in JavaScript

Tree_Inorder_Traversal/Tree_Inorder_Traversal.ts
Fixes #2552
-  Added Tree Inorder Traversal in TranScript language .
- 
- TransScript
- 
-  Tree_Inorder_Traversal.ts
- 
Thanks!
=> Tree_Inorder_Traversal in TypeScript

Extended_Euclidean_Algorithm/Extended_Euclidean_Algorithm.php
Fixes #2906
- Program for Extended Euclidean Algorithm in PHP
- PHP
- Extended_Euclidean_Algorithm.php
Thanks!
=> Extended Euclidean Algorithm in PHP

Postman_Sort/Postman_Sort.dart
Fixes #2251 
- Postman sort implemented in Dart
- Dart
- Postman_Sort.dart
Thanks!
=> Postman sort implemented in Dart - #2251 resolved

Extended_Euclidean_Algorithm/Extended_Euclidean_Algorithm.dart
Fixes #2906
- [ ✔  ] 4 space indentation.
- [  ✔ ] Coding conventions are followed.
- [  ✔ ] Input is taken dynamically.
- [  ✔ ] Sample Input / Output is added at the end of file.
- [  ✔ ] Logic Documentation (Comments).
- [  ✔ ] File names are correct.
-  Extended Euclidean Algorithm in Dart
- Dart
- Extended_Euclidean_Algorithm.dart
Thanks!
=> Extended Euclidean Algo in Dart

Longest_Increasing_Subsequence/README.md
Fixes #2253 
- Documentation (README.md for LIS)
- Markdown (md)
- README.md
Thanks!
=> README for Longest Increasing Subsequence

Red_Black_Tree/Red_Black_Tree.dart
Fixes #2163 
- Red black tree is implemented in Dart
- Dart
- Red_Black_Tree.dart
Thanks!
=> Red black tree implemented in Dart - #2163 resolved

Karatsuba_Algorithm/Karatsuba_Algorithm.rb
Fixes #2248 
- Karatsuba Algorithm In Ruby
- 
- Ruby
- 
- Karatsuba_Algorithm.rb
- 
Thanks!
=> Karatsuba Algorithm In Ruby

Tree_Postorder_Traversal/Tree_Postorder_Traversal.ts
Fixes #2551
- Add code for Tree Postorder Traversal in TypeScript 
- TypeScript
- Tree_Postorder_Traversal.ts
Thanks!
=> Add Tree Postorder Traversal in TypeScript

Tree_Preorder_Traversal/Tree_Preorder_Traversal.ts
Fixes #2550
-  Implementation of preorder traversal in typescript
- 
-  TypeScript
- 
-  Tree_Preorder_Traversal.ts
- 
Thanks!
=> Implementation of preorder traversal in typescript

Longest_Increasing_Subsequence/Longest_Increasing_Subsequence.kt
Fixes #2253 
- Add LIS in Kotlin
- Kotlin
- LongestIncreasingSubsequence.kt
Thanks!
=> Longest_Increasing_Subsequence

Knuth_Morris_Pratt_Algorithm/Knuth-Morris_Pratt_Algorithm_README.md
Fixes #2555 
- ADDED NEW FILE
- 
- 
- 
- Knuth-Morris_Pratt_Algorithm_README.md
- 
Thanks!
=> Knuth-Morris algo readme

Quick_Sort/Quick_Sort.rs
Fixes #2131 
- Added Quick Sort in Rust
- Rust
- Quick_Sort.rs
Thanks!
=> Quick sort in Rust

Ternary_Search/Ternary_Search.rb
Fixes #2176 
- Added ternary search in ruby
- Ruby
- 
- Ternary_Search.rb
- 
Thanks!
=> Added Ternary_Search.rb
