Interpolation_Search/Interpolation_Search.go, Interpolation_Search/Interpolation_Search.py
=> add Interpolation_Search.go

Binary_Search/Binary_Search.go
=> add Binary_Search.go

Activity_Selection/activity_selection.go
=> add activity_selection.go

Breadth_First_Search/Breadth_First_Search
=> Added Breadth First Search in Java

Dijkstra_Algorithm/DijkstrasAlgo.java
1. Added implementation of Dijkstra's Algorithm in JAVA
2. Open for updates in efficiency
=> Dijkstra's Algoritm in JAVA

Stacks_Using_Queues/Push_Efficient.java
Implemented Stack Using Queues.
implemented : push efficient algorithm big-oh(1)
=> Push Efficient

Stacks_Using_Queues/Pop_Efficient.java, Stacks_Using_Queues/Push_Efficient.java
Implemented Stacks using Queues.
1. Pop Efficient
2. Push Efficient
=> Stack using queues java

LinkedList/Linked_List.java, Stacks_Using_Queues/Pop_Efficient.java, Stacks_Using_Queues/Push_Efficient.java
Added reverse linked list functionality
=> Reversed linked list

reversal_ll.c
This is a C program to reverse a linked list.
=> Sahilrider patch 1

Bellmanford_Algorithm/bellmanford.cpp
Added Bellmanford algorithm for shortest path
#159
=> Bellmanford algorithm added

Chinese_Remainder_Theorem/Chinese_Remainder_Theorem.java
=> Adds Java implementation of Chinese Remainder Thoerem

tree_inorder.c, tree_postorder.c, tree_preorder.c
Inorder transversal of tree using C
=> Transversal of tree using C

Segment_Tree_RMQ/Segment_Tree_RMQ.java
=> Added Segment Tree

LinkedList_Bubble_Sort/LinkedList_Bubble_Sort.java, Shell_Sort/Shell_Sort.java
I originally wanted to implement it in a modular way but I was concerned it may conflict with other files so I had to keep it enclosed.
Will be implementing the insertion and selection sorts in a different language in the near future.
Feedback is much appreciated! :)
From: [Issue #155 ](https://github.com/jainaman224/Algo_Ds_Notes/issues/155)
=> Added LinkedList Bubble Sort in Java

Queue_Using_Arrays/Queue_Using_Arrays.py
Implemented queue using arrays in python2.
Refrenced issue #177
=> Implemented queue using arrays in python2

Dynamic_Stack_Arrays/Dynamic_Stack.c
=> Dynamic stack using arrays

Queue_Using_Arrays/Queue_Using_Arrays.c
=> Queue using array in c

Linear_Search/README.md
=> Added linear search readme

Linked_List/Linked_List.cpp
Added iterative and recursive implementations of Linked List length
checking functions.
Refer to #213
=> [C++] Add Linked List length functions

Sleep_Sort/sleep_sort.erl
#130 :Added sleep sort in erlang.
I was working on python but sleep sort was already implemented in python,
so implementing it in erlang.
Please let me know in case of any query.
=> Implemented sleep sort in erlang

Ford_Fulkerson_Method/Ford_Fulkerson_Method.java
Maximum Flow algorithm Ford Fulkerson added for java. #161
=> Added Ford Fulkerson Method for JAVA

Linked_List_Bubble_Sort/Linked_List_Bubble_Sort.java, Linked_List_Selection_Sort/Linked_List_Selection_Sort.java, Linked_List_Selection_Sort/Linked_List_Selection_Sort.rb
Also changed some text in other files so it would compile properly.
Feedback is much appreciated!
=> Added LinkedList Selection Sort in Ruby

Dijkstra_Algorithm/dijkstra.cpp
=> implementation of dijkstra algorithm using priority queue.

Binary_Search_Trees/BinarySearchTree.cpp
As mentioned on gitter I'm not happy with the Binary Search Tree C++ implementation: It needlessly uses a global variable, has a humongous memory leak (never freeing anything) and pretty much uses no C++ features at all.
In lieu of long asynchronous discussions I quickly made the changes I feel are reasonable. I did not go overboard adding templates, noexcept declarations or other advanced C++ features (as I may have in #239), but I did use std::unique_ptr (and thus std::move) because manual memory management has no place in modern C++. (See also the [C++ Core Guidelines](isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines).)
=> improve C++ binary search tree

Linked_List_Bubble_Sort/Linked_List_Bubble_Sort.cpp, Queue_Using_Linked_List/Queue_Linked_List.java, Queue_Using_Linked_List/Queue_Linked_List.py, Reversal_Linked_List/Reversal_Linked_List.py
=> Queue linked list python

Ford_Fulkerson_Method/Ford_Fulkerson_Method.py
=> Add Ford Fulkerson implementation for Python

Priority_Queue/HeapPriorityQueue.java
This is a basic java implementation of a Java priority queue based on the heap minimum property
=> Add a simple java Priority Queue implementation

Topological_Sort/Topological_Sort.cpp
=> Added C++ solution for Topological Sort

Ford_Fulkerson_Method/Ford_Fulkerson_Method.py, Queues_Using_Stacks/Efficient_Enqueue.c
=> Queues using Stacks with Optimized Enqueue policy

Ordered_doubly_linked_list/Ordered_doubly_linked_list.hpp
Simple ordered doubly linked list that allows usage with any data structure to be saved as an item in a node.
=> Added ordered doubly linked list algo in C++

Kruskal_Algorithm/Kruskal_Algorithm.cpp
Hi, I implemented a new findParent function using path compression to make it faster than the old one. #158
=> add path compression function for Kruskal Algorithm implemented in C++

Fenwick_Tree/FenwickTree.cpp
Hi, I think Fenwick Tree (or Binary Indexed Tree) is a good data structure for learning.
It's a special case of segment tree which can update a single element and query the prefix sum of an array efficiently.
Thanks a lot! :)
=> Fenwick Tree implementation

Priority_Queue/LeftistPriorityQueue.cpp
Add a "Leftist Tree" implementation version of priority queue.
Leftist Tree is a mergeable heap implementation which might give a great help. :) #156
=> Leftist Tree version Priority Queue implemenataion

Euclidean_Algorithm/Euclidean_Algorithm.cpp
I added a new implementation of gcd in code.
It's pretty amazing and I like it very much.
Thanks a lot ! :)
=> add another implementation for GCD

Bubble_Sort/Bubble_Sort.c
=> Bubble_Sort.c

Binary_Tree/Binary_Tree.c, Tree_Levelorder_Traversal/Tree_Levelorder_Transversal.c
- Binary Tree
- Tree Level-order Transversal
Implemented in c
also addresses #174
=> Binary Tree + level-order transversal in c

Boyer_Moore_Algorithm/boyer_moore.cpp, Boyer_Moore_Algorithm/boyer_moore.py
=> Boyer Moore Implmentation in c++ and python

Stacks_Using_Queues/Stack.py
Solves #152 in python. Documentation will be coming soon.
=> Stack implementation using Queues Python

Binary_Search/Binary_Search.cpp
These are slightly more powerful implementations of binary search:
- Lower bound: searches for element greater than or equal given number
- Upper bound: searches for element strictly greater than given number
=> Lower bound & Upper bound

Treap/Treap.cpp
Added treap with insert and find operations.
=> Added treap data structure

Queue_Using_Linked_List/Queue_Linked_List.c
Implemented queue using linked list in C
Ref issue #178
=> Implemented queue using linked list in C

Prims_Algorithm/Prims_Algorithm.c
=> add prims algorithm in C

Circular_Linked_List/Circular_Linked_List.c, Dijsktra_Algorithm/Dijsktra_Algorithm.c, Merge_Sort/Merge_Sort.c
- Circular Linked List
- Dijsktra Algorithm
- Merge Sort 
all implemented in c.
Also addresses #159
=> Some algorithms in c

Insertion_Sort/Insertion_Sort.c
Implementation of insertion sorting in C
Closes: #318
=> Implemented insertion sorting in C

Selection_Sort/Selection_Sort.c
=> Implemented Selection Sort Algorithm in C

Prefix_function/Prefix_function.cpp
Prefix function calculation and working example.
=> Added prefix function

Dynamic_Programming_Fibonacci_Numbers/fib.cpp
dynamic programming example for Fibonacci numbers
=> dynamic programming example

Inheritance(C++)/README.md
=> corrected multilevel inheritance image

Linear_Search/Linear_Search.c
Implemented Linear search in C. 
Ref issue #372
=> Implemented Linear Search in C

Queue_Using_Linked_List/Queue_using_template_linked_list/Queue.cpp, Queue_Using_Linked_List/Queue_using_template_linked_list/Queue.h
This is kind of the standard implementation for frequently used data structures, so pushed it anyway. Please decide whether to get it in or not.
=> C++ / Add Generic queue to support int, double, short, float etc.

shaker_sort/Shaker_sort.java, shaker_sort/shaker_sort.c
solved issue with previous code and added  in java as well
=> added shaker sort in java bug fixed

Heap_Sort/Heap_Sort.java
changed methods names to resolve the issue
=> issue #405 resolution

AVL_Tree/AVL_Tree.c
=> Added AVLTree in C

Red_Black_tree/RedBlackTrees.c
Red Black Tree implementation in C.
=> Added Red Black Tree in c

Ternary_Search/Ternary_Search.coffee, Ternary_Search/Ternary_Search.cpp, Ternary_Search/Ternary_Search.js
Signed-off-by: nihalChauhan <nihalchauhan16@gmail.com>
=> Ternary Search : js

Activity_Selection/activity_selection.js
Signed-off-by: nihalChauhan <nihalchauhan16@gmail.com>
=> Activity Sel : js

Sieve_Of_Eratosthenes/Sieve_Of_Eratosthenes.js
Signed-off-by: nihalChauhan <nihalchauhan16@gmail.com>
=> Sieve of E : js

Linked_List/LinkedList.js
Implementation of singly linked list in javascript
=> linked list in javascript

Linked_List/LinkedList.js
=> Overide toString to print LinkedList

Trie_For_Words/Trie.py
=> add python implementation of word trie

Trie_For_Natural_Numbers/Trie.py
add natural number trie in python
=> add python implementation of natural number trie

Binary_Search/searching_a_circularly_sorted_array.cpp
CPP code for searching a circularly sorted array
=> searching a circularly sorted array

Linked_List_Selection_Sort/Linked_List_Selection_Sort.c
=> Implemented Linked list selection sort in C

Depth_First_Search/Depth_First_Search.java
Added DFS program in java. Programmed using the existing py and cpp files as a reference for encouraging improved understandability.
=> Added Depth_First_Search java program

Binary_Heap/Binaryheap.cpp
added code for implementation of binary heap and extract min in cpp.
=> Added Binary_heap

Priority_Queue/HeapPriorityQueue.c
Standard implementation with some extra functionalities like decrease priority, extract min and get min, for better understanding
=> Priority Queue using Heap in c language

Insertion_Sort/Insertion_Sort.js, Quick_Sort/Quick_Sort.js, Selection_Sort/Selection_Sort.js
Implemented Insertion Sort , Quick Sort, Selection Sort in JavaScript
=> Solved Issue-460

Fenwick_Tree/Fenwick_Tree.py
Fenwick_Tree.py have been added in Fenwick_Tree with code explanation. Uploaded code is test with given test case.
=> Fenwick_Tree.py added

Binary_Search_Trees/README.md
Added the README.md file along with links to implementation.
Fixes #485
=> Fixes #485 - Added README.md for Binary Search Trees

Dynamic_Stack_Arrays/Dynamic_Stack.cpp, Topological_Sort/Topological_Sort.java
I have created a new file Topological_Sort.java which contains the code for implementation of Topological sort in java. I have created this file in the folder named Topological_Sort.
=> Fixes #160 Graph Algorithm - Topological_Sort in java added

Cocktail_Sort/Cocktail_Sort.java
I have implemented cocktail sort in java. this is in reference to the issue #548.
=> Fixes #548 Cocktail sort in java

Comb_Sort/comb_sort.cpp, Comb_Sort/comb_sort.go, Comb_Sort/comb_sort.java, Comb_Sort/comb_sort.py
=> Added Comb Sort in C++, Java, Python, Go

Cocktail_Sort/Cocktail_Sort.js
I have implemented cocktail sort in javascript which refers to the issue #584 .
=> Fixes #584 cocktail sort in js added

Bellmanford_Algorithm/Bellmanford.c, Heap_Sort/Heap_Sort.c, Kadane_Algorithm/Kadane_Algorithm.js
I have implemented heap sort in c which solves the issue #599 .
=> Fixes #599 heap sort in c added

anagram/anagram_string.js, anagram/anagram_string.py
Anagrams implemented in js and python
=> Solved Issue 474

AVL_Tree/AVL_Tree.java
Java implementation of AVL Trees.
=> Issue #581:  Created AVL_Tree.java

Z_Algorithm/Z_Algorithm.c
Added Zalgorithm in c and fixed indentation errors in it.
=> Added Z algorithm in C

TimSort/README.md
@rishabhgarg25699 do review it
=> Create README.md of TimSort

Longest_Common_Subsequence/Longest_Common_Subsequence.cpp, Longest_Common_Subsequence/Longest_Common_Subsequence.go, Longest_Common_Subsequence/Longest_Common_Subsequence.java, Longest_Common_Subsequence/Longest_Common_Subsequence.py
=> Longest Common Subsequence in C++, Java, Python ,Go

Stacks_Using_Linked_Lists/README.md
I have added README.md for stacks using linked lists.
Refer to issue #466
=> Add README.md for Stacks using Linked Lists

Optimal_Binary_Search_Tree/Optimal_Binary_Search_Tree.cpp
=>  Optimal_Binary_Search_Tree (issue # 604)

Tower_Of_Hanoi/Tower_Of_Hanoi.js
Added Tower Of Hanoi in Javascript
=> Solved Issue-537

Queue_Using_Stacks/Queues_Using_Stacks.cpp, Queue_Using_Stacks/Queues_Using_Stacks.js
=> Added queue_using_stack in Javascript and cpp

README.md, floating_point_arithmetic/README.md, floating_point_arithmetic/float_add.py, floating_point_arithmetic/float_divide.py, floating_point_arithmetic/float_multiply.py, floating_point_arithmetic/float_substract.py
=> floating point arithmetic in python

Edit_Distance_Algorithm/Edit_Distance.java, Edit_Distance_Algorithm/Edit_Distance.js, Edit_Distance_Algorithm/Edit_Distance.py, Edit_Distance_Algorithm/Edit_distance.cpp
Implementation in reference to issue #613 . Added four separate files in each language.
=> Fixes #613 edit distance algo in cpp,java,py,js

Connected_Components_Undirected_Graph/Connected_Components_Undirected_Graph.cpp
=> Connected Components in an Undirected graph in C++

Binary_Insertion_Sort/Binary_Insertion_Sort.c, Binary_Insertion_Sort/Binary_Insertion_Sort.cpp
=> Binary Insertion Sort in c and c++ 

Exponential_Search/Exponential_Search.c, Exponential_Search/Exponential_Search.cpp
=> Exponential_Search 

Mo's_Algorithm/Mo's_Algorithm.cpp
=> Mo's_Algorithm

Treap/README.md, Treap/Treap.py
Implementation of Treap in python along with README 
Refer  #452
=> Treap implementation in python along with README - #452 #gssoc19

Tower_Of_Hanoi/Tower_Of_Hanoi.js
I'm GSSoC participant.
While working with README.md( #678 ) for ToH I found two bugs in the code so I fixed them.
=> Fixed error in Tower_Of_Hanoi.js

Tower_Of_Hanoi/README.md
I have added README.md for Tower of Hanoi
Refer to issue #678
=> Add README.md for Tower of Hanoi

Bucket_Sort/Bucket_Sort.py
=> Added Bucket Sort in Python

Prefix_Sum/Prefix_Sum.cpp
Efficient algorithm to compute the sum of the elements between two given indices in O(1), i.e., constant time. The value of sum of elements from index L to R is v[R] - v[L-1] for L>0, and v[R] for L=0.
=> Added Prefix Sum in C++

pancake_sort/pancake_sort.cpp, pancake_sort/ps.cpp
added pancake sort code in cpp;# issue 596
=> added pancake sort code in cpp# issue 596

Pigeonhole_Sort/Pigeonhole_Sort.c, Pigeonhole_Sort/Pigeonhole_Sort.cpp
=> Pigeonhole_Sort

Graph_Colouring_Algorithm/Graph_Colouring.py
I have implemented Graph Colouring Algorithm in Python which solves issue #633.
=> Fixes #633: Implemented Graph Colouring Algorithm in Python

Quick_Sort/README.md
Added the readme.md for Quick Sort algorithm that fixes issue #726.
=> Fixed #726 - Added readme.md for QuickSort

Pascal's_Triangle/Pascal's_Triangle.c, Pascal’s_Triangle/Pascal’s_Triangle.cpp
=> Pascal's_Triangle

Burrows_Wheeler_Transformation_Algorithm/BWT.py
@jainaman224 I was not able to delete those previous commits from my last PR #690. So, I made this new PR. I tried to rebase those commits from my local repo and I successfully did also. But was not able to reflect those changes in the PR. Kindly review and merge this one and provide me advice over the same.
=> Added comments

Doubly_Linked_List/Doubly_Linked_List.c
I'm GSSoC participant
I have added Doubly Linked List in C
Refer to issue #718
=> Added doubly linked list in C

Strassens_Algorithm/Strassens_Algorithm.c, Strassens_Algorithm/Strassens_Algorithm.java
Added c and java implementation of strassen's algorithm for matrix multiplication.
=> Added strassen algorithm in c and java

Merge_Sort/README.md
Fixed #771; added readme.md for Merge Sort algorithm.
=> Solved #771 Added readme for Merge Sort

Knapsack_Fractional/Knapsack_Fractional.cpp, Knapsack_Fractional/Knapsack_Fractional.java, Knapsack_Fractional/Knapsack_Fractional.py
=> Fractional Knapsack in C++, Java, Python

Euler_Totient_Function/Euler_Totient_Function.cpp, Euler_Totient_Function/Euler_Totient_Function.java, Euler_Totient_Function/Euler_Totient_Function.py
=> Added Euler totient function

Prims_Algorithm/Prims_Algorithm.java
=> Added Prims Algorithm in Java

Egg_Drop/EggDrop.java, Egg_Drop/Egg_Drop.java
#794 Implemented Egg Drop problem in Java.
Recursive, Recursive Dynamic Programming and Iterative Solution provided.
=> Egg_Drop problem implemented in Java

Tree_Spiralorder_Traversal/Tree_Spiralorder_Traversal.cpp
My issue #800 referencing #174
=> Spiral Order Traversal of Binary Tree

Prime Factorization/Prime_Factorization.cpp, Prime Factorization/Prime_Factorization.java, Prime Factorization/Prime_Factorization.py
=> Added Prime Factorization

Longest_Common_Substring/Longest_Common_Substring.cpp, Longest_Common_Substring/Longest_Common_Substring.java, Longest_Common_Substring/Longest_Common_Substring.py, Longest_Common_Substring/README.md
Added C++, Java and Python Code of Longest Common SubString.
Issue: [#667](https://github.com/jainaman224/Algo_Ds_Notes/issues/667)
=> Added C++, Java and Python Code of Longest Common SubString. Issue #667

Tree_Verticalorder_Traversal/Tree_Verticalorder_Traversal.cpp, Tree_Verticalorder_Traversal/Tree_Verticalorder_Traversal.java, Tree_Verticalorder_Traversal/Tree_Verticalorder_Traversal.py
My issue #799 referencing #174
=> Vertical Order Traversal of Binary Tree in C++, Java and Python

.github/pull_request_template.md
Fixed typo for 'conventions' in PR template.
=> Fixed typo in pull_request_template.md

Tree_Spiralorder_Traversal/Tree_Spiralorder_Traversal.java, Tree_Spiralorder_Traversal/Tree_Spiralorder_Traversal.py
Fixes #814 
-  Added Spiral Order Traversal in Binary Tree in other languages
-  Java
- Python
- Tree_Spiralorder_Traversal.java
- Tree_Spiralorder_Traversal.py
=> Spiral Order Traversal in Binary tree

Connected_Components_Undirected_Graph/Connected_Components_Undirected_Graph.py
Issue: [#740](https://github.com/jainaman224/Algo_Ds_Notes/issues/740)
=> Connected Components in an Undirected graph in Python3

RSA_Algorithm/RSA_Algorithm.c, RSA_Algorithm/RSA_Algorithm.cpp, RSA_Algorithm/RSA_Algorithm.java, RSA_Algorithm/RSA_Algorithm.py
Fixes #837
- Code for RSA algorithm added.
- C/C++
- Java
- Python
- RSA_Algorithm.c
- RSA_Algorithm.cpp
- RSA_Algorithm.java
- RSA_Algorithm.python
=> RSA code for C/C++, Java, Python added

Bead_Sort/Bead_Sort.c, Bead_Sort/Bead_Sort.java, Bead_Sort/Bead_Sort.py
Fixes #819 
- Addition of Bead Sort algorithm
- C
- Java
- Python
- Bead_Sort.c
- Bead_Sort.java
- Bead_Sort.py
=> Added BeadSort Algorithm (#819)

Activity_Selection/Activity_Selection.c, Activity_Selection/Activity_Selection.cpp, Activity_Selection/Activity_Selection.go
Fixes #853 
Referencing #859 
- Fixed wrong example quoted
- Add input and output
- Added comments
- Modifications in logic, indentation etc.
- C
- C++
- Go
- Activity_Selection.c
- Activity_Selection.cpp
- Activity_Selection.go
=> Fixes in Activity Selection in C, C++, Go

Prefix_Sum/Prefix_Sum.go, Prefix_Sum/Prefix_Sum.java, Prefix_Sum/Prefix_Sum.py
Fixes #870  
- Added implementation for finding the prefix sum array in java, go and python.
- Java
- Go
- Python
- Prefix_Sum.java
- Prefix_Sum.go
- Prefix_Sum.py
=> Added Prefix Sum

Activity_Selection/Activity_Selection.java, Activity_Selection/Activity_Selection.py, Activity_Selection/activity_selection.js
Fixes #853 
Referencing #859 
- Fixed wrong example quoted
- Add input and output
- Added comments
- Modifications in logic, indentation etc.
- Java
- JavaScript
- Python
- Activity_Selection.java
- Activity_Selection.js
- Activity_Selection.py
=> Fixes in Activity Selection in Java, JavaScript and Python

Nim_Game/Nim_Game.cpp, Nim_Game/Nim_Game.java, Nim_Game/Nim_Game.py
Fixes #713 
- Added implementation of Nim game in C++, Java and Python.
- C++
- Java
- Python
- Nim_Game.cpp
- Nim_Game.java
- Nim_Game.py
=> Added Nim Game

Exponential_Search/Exponential_Search.cs, Exponential_Search/Exponential_Search.java, Exponential_Search/Exponential_Search.js, Exponential_Search/Exponential_Search.py
I have implemented exponential search in java, javascript, python and c# which fixes issue #793 .
=> Fixes #793: exponential search added

Longest_Palindromic_Substring/Longest_Palindromic_Substring.cpp, Longest_Palindromic_Substring/Longest_Palindromic_Substring.java, Longest_Palindromic_Substring/Longest_Palindromic_Substring.py
Fixes #830  
- Added Implementation of Finding longest palindromic substring of a given string in C++,Java and Python.
- C++
- Java
- Python
- Longest_Palindromic_Substring.cpp
- Longest_Palindromic_Substring.java
- Longest_Palindromic_Substring.py
=> Added Longest Palindromic Substring

Prefix_Sum/Prefix_Sum.c
Fixes #849
- Added Prefix_Sum.c
- C
- Prefix_Sum.c
=> Added Prefix Sum in C

BFS_On_Matrix/BFS_On_Matrix.cpp, BFS_On_Matrix/BFS_On_Matrix.java, BFS_On_Matrix/BFS_On_Matrix.py
Fixes #798 
-  Added implementation for shortest path between source and destination cells in a matrix using Breadth First Search
- C++
- Java
- Python
- BFS_On_Matrix.cpp
- BFS_On_Matrix.java
- BFS_On_Matrix.py
=> Shortest Path between two cells in a Matrix using BFS

Lucas Theorem/Lucus_Theorem.cpp
=> Added Lucus Theorem

Russian-Peasant Multiplication/Russian_Peasant_Multiplication_Algo.c
=> Added Russian-Peasant Multiplication Algorithm

Dynamic_Programming_Rod_Cutting/README.md
Fixes #523 
- README.md is added 
- Plain English text
- README.md
=> Created README.md for Dynamic_Programming_Rod_Cutting

Bellmanford_Algorithm/README.md
=> add README.md for Bellmanford algo

Red_Black_Tree/RedBlackTree.java
Fixes #768
[x] 4 space indentation.
[x] Coding conventions are followed.
[x] Sample Input / Output.
[x] Logic Documentation (Comments).
[x] File names are correct.
- Adding Red Black Trees Implementation in java
- Java
- Red_Black_Tree/RedBlackTree.java
=> Red Black Trees in java

Matrix_Operations/C++/Idempotent_Matrix.cpp, Matrix_Operations/C++/Matrix_Lower_triangular.cpp, Matrix_Operations/C++/Matrix_Multiplication_Recursive.cpp, Matrix_Operations/C++/Matrix_Upper_triangular.cpp, Matrix_Operations/C++/Sum_Of_Middle_Row_And_Column.cpp
#450
Matrix operation: Matrix Multiplication | Recursive, Sum of middle row and column in Matrix, print Lower triangular, print Upper triangular and check idempotent matrix.
=> Matrix operation in c++

Longest_Repeating_Subsequence/Longest_Repeating_Subsequence.cpp, Longest_Repeating_Subsequence/Longest_Repeating_Subsequence.java, Longest_Repeating_Subsequence/Longest_Repeating_Subsequence.py
Fixes #844  
-  Longest Repeating Subsequence using Dynamic Programming
-  C++
-  Java
- Python
-  Longest_Repeating_Subsequence.cpp
-  Longest_Repeating_Subsequence.py
- Longest_Repeating_Subsequence.java
=> Longest repeating subsequence in C++, Java and Python #844

Cocktail_Sort/Cocktail_Sort.c
Fixes #538 
- Added Cocktail Sort in c
- C
- Cocktail_Sort.c
=> Added Cocktail Sort in c

Segment_Tree_With_Lazi_Propagation/Segment_Tree_With_Lazy_Propagation.py
Fixes #911  
- Added Separate folder for Segment Tree with Lazy Propagation. In future i will upload code for the same algorithm in java, cpp and php.
- Added Segment_Tree_With_Lazy_Propagation.py file
- Python
- Segment_Tree_With_Lazy_Propagation.py
=> Segment Tree with Lazy Propagation in python

Inversions_Count/Inversions_Count.cpp
Fixes # 
- Added Inversions Count using Merge Sort approach
- C++
- Inversions_Count.cpp
=> Added Inversion Count using merge sort

Bresenham_Circle_Drawing_Algo/bresenham_circle_algo.c, Bresenham_Circle_Drawing_Algo/bresenham_circle_algo.cpp
Fixes #792 
- Code for bresenham circle drawing algo
- C
- C++
- bresenham_circle_algo.c
- bresenham_circle_algo.cpp
=> added code for bresenham circlo algo in c & c++

Scheduling_Algorithm/C++/Non_Preemptive/First_Come_First_Served.cpp, Scheduling_Algorithm/C++/Non_Preemptive/Priority_Scheduling.cpp, Scheduling_Algorithm/C++/Non_Preemptive/Shortest_Job_First.cpp, Scheduling_Algorithm/C++/Preemptive/Shortest_Remaining_Time_First.cpp
Fixes #876
- added Scheduling_Algorithm
- C++
- 
- First_Come_First_Served.cpp
- Priority_Scheduling.cpp
- Shortest_Remaining_Time_First.cpp
- Shortest_Job_First.cpp
=> Added Scheduling_Algorithm

DDA_Line_Drawing_Algorithm/DDA_Line_Drawing_Algo.c, DDA_Line_Drawing_Algorithm/DDA_Line_Drawing_Algo.cpp
Implemented DDA line algo in C & C++ 
need some time for implementing in java
=> added DDA line drawing code for c & c++

Babylonian_Method/Babylonian_Method.c, Babylonian_Method/Babylonian_Method.cpp
Fixes #915 
- Added Babylonian method in c and c++
- C
- C++
- Babylonian_Method.c
- Babylonian_Method.cpp
=> Added Babylonian Method in c and c++

CycleSort/Cycle_Sort.cpp, CycleSort/Cycle_Sort.java, CycleSort/README.md
Fixes #845
- Cycle sort added in cpp and java
-
- cpp
- java
-  CycleSort/Cycle_Sort.cpp
- CycleSort/Cycle_Sort.java
=> Cycle sort added in C++ and Java with README

Heap_Sort/README.md
Fixes #902 
- Add README.md for HeapSort
- README.md
=> Create README.md for HeapSort

Topological_Sort/Topological_Sort.c
=> Topological_Sort in c

Egg_Drop/Egg_Drop.py
- Added the Python implementation of the Egg Drop problem
- Python
- Egg_Drop.py
=> Added Egg Drop.py 

Radix_Sort/README.md
Fixes #760 
- Just added a Readme file for radix sort 
- Readme.md
=> Add readme file

Ugly_Number/Ugly_Number.c, Ugly_Number/Ugly_Number.cpp
Fixes #896 
- Added Ugly number in c and c++
- C
- C++
- Ugly_Number.c
- Ugly_Number.cpp
=> Added Ugly number in c and c++

Linked_List/Linked_List.rb
Fixes #939 
- implemented LinkedList in Ruby
- Ruby
- Linked_List.rb
=> added LinkedList in Ruby

Subset_Sum/Subset_Sum.cpp, Subset_Sum/Subset_Sum.java, Subset_Sum/Subset_Sum.py
Fixes #889 
-  Added Subset Sum Problem using Dynamic rogramming
- C++
-  Java
- Python
- Subset_Sum.cpp
- Subset_Sum.java
- Subset_Sum.py
=> Added Subset Sum Problem

Strassens_Algorithm/Strassens_Algorithm.py
Fixes #695 
- Implemented Strassen's Algorithm in Python for 2x2 matrix and NxN matrix
- Python
- Strassens_Algorithm.py	
- Strassens_Algorithm_Input_Size.py
=> Added Strassen's Algorithm in python

Lucas_Theorem/Lucas_Theorem.c
Fixes #952 
- Added Lucas Theorem in c
- C
- Lucas_Theorem.c
=> Added Lucas Theorem in c

Z_Algorithm/Z_Algorithm.rb
Fixes #940 
- Implemented the Z-Algorithm in Ruby
- Ruby
- Z_Algorithm.rb
=> Added Z_Algorithm in Ruby

Dijkstra_Algorithm/Dijkstra_Algorithm.rb
Fixes #937 
-  Implemented Dijkstra Algorithm with n^2 time complexity 
- Ruby
- Dijkstra_Algorithm.rb
=> Dijkstra Algorithm in Ruby

Longest_Palindromic_Subsequence/Longest_Palindromic_Subsequence.cpp, Longest_Palindromic_Subsequence/Longest_Palindromic_Subsequence.java, Longest_Palindromic_Subsequence/Longest_Palindromic_Subsequence.py
Fixes #831 
- Added longest palindromic subsequence in C++, Java, Python
- C++
- Java
- Python
- Longest_Palindromic_Subsequence.cpp
- Longest_Palindromic_Subsequence.java
- Longest_Palindromic_Subsequence.py
=> Added Longest Palindromic Subsequence

Linked_List_Quick_Sort/Linked_List_Quick_Sort.cpp, Linked_List_Quick_Sort/Linked_List_Quick_Sort.py, Sudoku_Solver/Sudoku_Solver.c, Sudoku_Solver/Sudoku_Solver.cpp, Sudoku_Solver/Sudoku_Solver.py
Fixes #875 
- write code of quicksort on the linked list in c++ and python
- c++
- python
- Linked_List_Quick_Sort.cpp
- Linked_List_Quick_Sort.py
Fixes #875 
@jainaman224 please review this PR.
=> quick sort on linked list

Egg_Drop/Egg_Drop.c, Egg_Drop/Egg_Drop.cpp
Fixes #994 
-  Added Egg Drop problem in C and C++
- C
- C++
- Egg_Drop.c
- Egg_Drop.cpp
=> Added Egg Drop

Bead_Sort/Bead_Sort.cpp
Fixes #1002 
- Added a C++ implementation for Bead sort with time complexity in range of O(1) and O(S), where S is sum of all elements in array.
- C++
- Bead_Sort.cpp
=> Beadsort implementation in C++

Postfix_To_Infix/Postfix_To_Infix.c, Postfix_To_Infix/Postfix_To_Infix.cpp
Fixes #978 
-  Added Postfix To Infix in C and C++
- C
- C++
- Postfix_To_Infix.c
- Postfix_To_Infix.cpp
=>  Added Postfix To Infix in C and C++

Queens_Problem/Queens_Problem.cpp
Fixes #951 
- Added N-Queens Problem in C++
- C++
- Queens_Problem.cpp
=> Added N-Queens Problem in C++

shaker_sort/Shaker_Sort.rb
Fixes #782 
- Implemented the Shaker Sort algorithm in Ruby language
- Ruby language
- Shaker_Sort.rb
=> added shaker sort in ruby

isBinary_Search_Tree/isbst.cpp
Fix #948
Check if a binary tree is a BST or not.
C++
isbst.cpp
=> Fix #948 isBST in c++

Ugly_Number/Nth_Ugly_Number.c, Ugly_Number/Nth_Ugly_Number.cpp
Fixes #1020
- added Nth Ugly Number
- C 
- C++
- Nth_Ugly_Number.c
- Nth_Ugly_Number.cpp
=> Nth Ugly Number in C and C++

Scheduling_Algorithm/C/Non_Preemptive/First_Come_First_Served.c, Scheduling_Algorithm/C/Non_Preemptive/Priority_Scheduling.c, Scheduling_Algorithm/C/Non_Preemptive/Shortest_Job_First.c, Scheduling_Algorithm/C/Preemptive/Shortest_Remaining_Time_First.c
Fixes #1019
- added Scheduling_Algorithm
- C 
- First_Come_First_Served.c
- Priority_Scheduling.c
- Shortest_Remaining_Time_First.c
- Shortest_Job_First.c
=> Scheduling Algorithm

Count_Inversion/Count_Inversion.js
Fixes #921  
Count inversion algorithm using merge sorts added.
- Javascipt
- Count_Inversion.js
=> Count Inversion algorithm is added

Pancake_Sort/Pancake_Sort.cpp, Ternary_Search/Ternary_Search.c
Fixes #1024 
- Added Ternary Search in C and pancake sort in C++
- C
- C++
- Pancake_Sort.cpp
- Ternary_Search.c
=> Ternary Search in C and pancake sort in C++

Fenwick_Tree/Fenwick_Tree.java, Fenwick_Tree/Fenwick_Tree.js
Fixes #922  
- Adding Fenwick Tree in Java
- Adding Fenwick Tree in JavaScript
- Java
- JavaScript
- Fenwick_Tree.java
- Fenwick_Tree.js
=> Added Fenwick Tree in Java and JavaScript

Stacks_Using_Arrays/Stacks_Using_Arrays.c
Fixes #1023
-  Added Stacks Using Arrays in c
- C
-  Stacks_Using_Arrays.c
=>  Stacks Using Arrays in c

Catalan_Numbers/Catalan_Numbers.cpp, Catalan_Numbers/Catalan_Numbers.java, Catalan_Numbers/Catalan_Numbers.py
Fixes #1054 
-  Added Catalan Numbers using Dynamic Programming
- C++
- Java
- Python
- Catalan_Numbers.cpp
- Catalan_Numbers.java
- Catalan_Numbers.py
=> Catalan Numbers using DP

Mo's_Algorithm/Mo's_Algorithm.c
Fixes #653 
- Added Mo's_Algorithm in C
- C
- Mo's_Algorithm.c
=> Mo's Algorithm

Queens_Problem/README.md
Fixes #1001 
- add docs of n-queens problem
- Markdown
- README.md
=> add docs of n-queens problem

Next_Smallest_Palindrome/Next_Smallest_Palindrome.cpp, Next_Smallest_Palindrome/Next_Smallest_Palindrome.cs, Next_Smallest_Palindrome/Next_Smallest_Palindrome.java, Next_Smallest_Palindrome/Next_Smallest_Palindrome.py
Fixes #886 
- Implementation of next smallest palindrome of a number.
- c++
- java
- python
- c#
-  Next_Smallest_Palindrome.cpp
- Next_Smallest_Palindrome.java
- Next_Smallest_Palindrome.py
- Next_Smallest_Palindrome.cs
=> Next Smallest Palindrome

Painter's_Partition_Problem/Painter's_Partition_Problem.cpp, Painter's_Partition_Problem/Painter's_Partition_Problem.java, Painter's_Partition_Problem/Painter's_Partition_Problem.py
Fixes #874  
-  Added Painter's Partition Problem in C++, Java and Python
-  C++
- Java
- Python
- Painter's_Partition_Problem.cpp
- Painter's_Partition_Problem.java
- Painter's_Partition_Problem.py
=> Added Painter's Partition Problem

Number_Of_Islands/Number_Of_Islands.cpp, Number_Of_Islands/Number_Of_Islands.java, Number_Of_Islands/Number_Of_Islands.py
Fixes #815 
-  Added Number of Islands Problem in C++, Java and Python
- C++
- Java
- Python
-  Number_Of_Islands.cpp
-  Number_Of_Islands.java
-  Number_Of_Islands.py
=> Number of Islands Problem

Insertion_Sort/Insertion_Sort.go, Selection_Sort/Selection_Sort.go
Fixes #1071 
- Added Insertion Sort and Selection Sort in Go
- Go 
- Insertion_Sort.go
- Selection_Sort.go
=> Sorting Algorithms in Go

FCFS_Scheduling/FCFS_Scheduling.cpp, FCFS_Scheduling/FCFS_Scheduling.go, FCFS_Scheduling/FCFS_Scheduling.java, FCFS_Scheduling/FCFS_Scheduling.py
Fixes #1046  
- Added FCFS Scheduling Algorithm in C++, Java, Python & Golang
- C++
- Java
- Python
- Golang
- FCFS_Scheduling.cpp
- FCFS_Scheduling.java
- FCFS_Scheduling.go
- FCFS_Scheduling.py
=> Added FCFS Scheduling

Array_Rotation/Array_Rotation.java
Fixes #1061 
-  implementing rotation in an array.
- java
- Array_Rotation.java
=> added array rotation in java

Array_Rotation/Array_Rotation.rb
Fixes #1051 
- Implemented Array Rotation in Ruby
- Ruby
- Array_Rotation.rb
=> Array rotation

Quick_Select/Quick_Select.cpp, Quick_Select/Quick_Select.java, Quick_Select/Quick_Select.py
Fixes #1053 
-  Added Quick Select Algorithm in C++, Java and Python 
- C++
- Java
- Python
- Quick_Select.cpp
- Quick_Select.java
- Quick_Select.py
=> Added Quick Select Algorithm

Babylonian_Method/Babylonian_Method.go, Babylonian_Method/Babylonian_Method.java
Fixes #1063  
- Added Babylonian method in Java and Golang
- Java
- Go
- Babylonian_Method.java
- Babylonian_Method.go
=> Added Babylonian method in Go, Java

Array_Rotation/ArrayRotationUsingTempArray.java
For the issue #750
Fixes #750
- Added Array Rotation by d elements using temporary array in Java
-  Java
- ArrayRotationUsingTempArray.java
=> Array Rotation in Java using Temp Array (Issue #750)

Bloom_Filter/BloomFilter.py, Bloom_Filter/README.md
Fixes #863  
- Bloom Filter Implementation in python
- Bloom Filter README
- Python
- BloomFilter.py
- README.md
=> Bloom Filter implementation in python  with README

Floyd's_Cycle_Detection_Algorithm/Floyd's_Cycle_Detection_Algorithm.c
Fixes #1078 
- Added C code for Detecting Cycle from a linked list using Floyd's cycle detection algorithm
- C
- Floyd's_Cycle_Detection_Algorithm.c
=> Added Floyd's cycle detection algorithm in Linked List

Ugly_Number/Nth_Ugly_Number.go, Ugly_Number/Nth_Ugly_Number.java, Ugly_Number/Nth_Ugly_Number.py, Ugly_Number/Ugly_Number.java, Ugly_Number/Ugly_Number.py
Fixes #1075  
- Added code for finding Nth ugly number in Java, Python & Go
- Added code for finding if an input number is an Ugly number in Python and Java
- Java
- Python
- Go
- Nth_Ugly_Number.go
- Nth_Ugly_Number.java
- Nth_Ugly_Number.py
- Ugly_Number.java
- Ugly_Number.py
=> Added Ugly Number in Java, Py & Go

Coin_Change/Coin_Change.go, Dynamic_Programming_Rod_Cutting/Dynamic_Programming_Rod_Cutting.go, Subset_Sum/Subset_Sum.go
Fixes #1099 
- Added Solutions to classical DP problems in Golang
- Go
- Coin_Change.go
- Subset_Sum.go
- Dynamic_Programming_Rod_Cutting.go
=> Coin Change, Subset Sum and Rod Cutting in Go

Automorphic_Number/Automorphic_Number.c, Automorphic_Number/Automorphic_Number.cpp, Automorphic_Number/Automorphic_Number.java
Fixes #1106
- Automorphic Number in C, C++, Java
- C
- Java
- C++
- Automorphic_Number.c
- Automorphic_Number.cpp
- Automorphic_Number.java
=> Automorphic_Number

Armstrong_Number/Armstrong_Number.c, Armstrong_Number/Armstrong_Number.cpp, Armstrong_Number/Armstrong_Number.java, Armstrong_Number/Armstrong_Number.py
Fixes #1105 
- Armstrong_Number in C, C++, python, and java
- C
- C++
- Python
- Java
- Armstrong_Number.c
- Armstrong_Number.cpp
- Armstrong_Number.py
- Armstrong_Number.java
=>  Armstrong_Number

Euler_Totient_Function/Euler_Totient_Function.c, Euler_Totient_Function/README.md
Fixes #1098 
- Added Euler Totient Function in C language 
- Added a README.md file.
- C
- Euler_Totient_Function.c
- README.md
=> Added Euler_Totient_Function.c and README.md file

Interpolation_Search/Interpolation_Search.c, Interpolation_Search/Interpolation_Search.cpp
Fixes #1080
- Added Interpolation Search in C and C++
- C
- C++
- Interpolation_Search.c
- Interpolation_Search.cpp
=> Added Interpolation Search

Lazy_Propagation_Segmentation_Tree/Lazy_Propagation_Segmentation_Tree.cpp
Fixes #635 
- Added  Lazy Propagation Segmentation Tree (To find Sum and maximum)
- C++
- Lazy_Propagation_Segmentation_Tree.cpp
=>  Lazy Propagation Segmentation Tree

Sieve_Of_Eratosthenes/README.md, Sieve_Of_Eratosthenes/Sieve_of_Eratosthenes.c
Fixes #1114 
- Added Sieve of Eratosthenes in C
- Added README,md file
- C
- Sieve_of_Eratosthenes.c
- README.md
=> Added Sieve of Eratosthenes in C and README.md file

Comb_Sort/README.md
@marwahmanbir 
Fixes #998 
- README file 
- C language used for Example code
- README.md
=> README for Comb Sort Algorithm #998

Triangular_Number/Triangular_Number.c, Triangular_Number/Triangular_Number.cpp, Triangular_Number/Triangular_Number.java, Triangular_Number/Triangular_Number.py
Fixes #1112 
-Added  Triangular Numbers in C, C++, Java, and python
- C
- C++
- Python
- Java 
- Triangular_Number.c
- Triangular_Number.cpp
- Triangular_Number.py
- Triangular_Number.java
=> Triangular_Number

Taylor_series_Repo/Taylor_series_Horner_rule.c
Fixes #1060 
- Added Taylor series using Horner's Rule in C 
- C
- Taylor_series_Horner_rule.c
=> Added Taylor series in c

Maximum_Product_Subset_Array/Maximum_Product_Subarray.c, Maximum_Product_Subset_Array/Maximum_Product_Subarray.cpp, Maximum_Product_Subset_Array/Maximum_Product_Subarray.go, Maximum_Product_Subset_Array/Maximum_Product_Subarray.java, Maximum_Product_Subset_Array/Maximum_Product_Subarray.py
Fixes #1104  
- Added implementation to find Maximum Product Subarray of an array in C,C++,Java,Python & Golang.
- C
- C++
- Python
- Java
- Go
- Maximum_Product_Subset_Array.c
- Maximum_Product_Subset_Array.cpp
- Maximum_Product_Subset_Array.py
- Maximum_Product_Subset_Array.java
- Maximum_Product_Subset_Array.go
=> Added Maximum product Subarray

Depth_First_Search/Depth_First_Search.rb
Fixes #936 
- Implemented Depth First Search
- Ruby
- Depth_First_Search.rb
=> Depth First Search in Ruby

Binary_Tree_Bottom_View/Binary_Tree_Bottom_View.cpp, Binary_Tree_Bottom_View/Binary_Tree_Bottom_View.java, Binary_Tree_Bottom_View/Binary_Tree_Bottom_View.py
Fixes #1101 
- Added Bottom View of a Binary Tree
- C++
- Java
- Python
- Binary_Tree_Bottom_View.cpp
- Binary_Tree_Bottom_View.java
- Binary_Tree_Bottom_View.py
=> Added Bottom View of a Binary Tree

Segmented_Sieve/README.md, Segmented_Sieve/Segmented_Sieve.c, Segmented_Sieve/Segmented_Sieve.cpp
Fixes #1115 
- Added Segmented Sieve method in C and C++
- Added README.md
- C
- C++
- Segmented_Sieve.c
- Segmented_Sieve.cpp
- README.md
=> Added Segmented sieve in C, C++ and, README.md

Bresenham_Algo_Programs/Bresenham_Line_Algorithm.c, Bresenham_Algo_Programs/Bresenham_Line_Algorithm.java, Bresenham_Algo_Programs/Bresenham_Line_Algorithm.py
Fixes #841 
- Program For Bresenham line in c
- Program for Bresenham line in python
- Program for Bresenham line in java
- C
- Java
- Python
- Bresenham_Line_Algorithm
- bresenham_line
- Line_drawing_algo
=> Bresenham line drawing programs 

Minimum_Product_Subset_Array/Minimum_Product_Subset_array.c, Minimum_Product_Subset_Array/Minimum_Product_Subset_array.cpp, Minimum_Product_Subset_Array/Minimum_Product_Subset_array.go, Minimum_Product_Subset_Array/Minimum_Product_Subset_array.java, Minimum_Product_Subset_Array/Minimum_Product_Subset_array.py
Fixes #1103  
- Added implementation to find minimum product of a subset of an array in C, C++, Java, Python, Go
- C
- C++
- Java
- Python
- Go
- Minimum_Product_Subset_array.c
- Minimum_Product_Subset_array.cpp
- Minimum_Product_Subset_array.java
- Minimum_Product_Subset_array.py
- Minimum_Product_Subset_array.go
=> Added Minimum Product Subset Array

ASCII_SUBSEQUENCES/ASCII_SUBSEQUENCES.cpp, ASCII_SUBSEQUENCES/README.md
Fixes #1119 
- Added Implementation for ASCII SUBSEQUENCES using Recursion with proper comments and indentation in C++  programming languages along with a README.md file.
- C++
- ASCII_SUBSEQUENCES/ASCII_SUBSEQUENCES.cpp 
- ASCII_SUBSEQUENCES/README.md
=> Added ASCII SUBSEQUENCES in C++ and README.md

Next_Greater_Element/Next_Greater_Element.cpp, Next_Greater_Element/Next_Greater_Element.java, Next_Greater_Element/Next_Greater_Element.py
Fixes #1100 
- Added next greater element using stack
- C++
- Java
- Python
- Next_Greater_Element.cpp
- Next_Greater_Element.java
- Next_Greater_Element.py
=> Next Greater Element using stack

Binary_Tree_Left_View/Binary_Tree_Left_View.cpp, Binary_Tree_Left_View/Binary_Tree_Left_View.java, Binary_Tree_Left_View/Binary_Tree_Left_View.py
Fixes #1152 
- Added Binary Tree Left View
- C++
- Java
- Python
- Binary_Tree_Left_View.cpp
- Binary_Tree_Left_View.java
- Binary_Tree_Left_View.py
=> Left View of a Binary Tree

Armstrong_Number/Armstrong_Number.kt, Automorphic_Number/Automorphic_Number.kt
Fixes #1136  
- Adding Automorphic Number Algorithm in Kotlin
- Adding Armstrong Number Algorithm in Kotlin
- Kotlin
- Automorphic_Number.kt
- Armstrong_Number.kt
=> Adding Automorphic and Armstrong Number Algo

Mystery_Number/Mystery_Number.c, Mystery_Number/Mystery_Number.cpp, Mystery_Number/Mystery_Number.go, Mystery_Number/Mystery_Number.java, Mystery_Number/Mystery_Number.py
Fixes #1148  
- Added Implementation for Mystery Number in C, C++, Java, Python, Golang
- C
- C++
- Java
- Python
- Golang
- Mystery_Number.py
- Mystery_Number.c
- Mystery_Number.cpp
- Mystery_Number.java
- Mystery_Number.go
=> Added Mystery Number

Bresenham_Circle_Drawing_Algo/Bresenham_Circle_Algorithm.py
Fixes #971 
- Added a Bresenham Circle Program In python using pygame 
- Python
- Bresenham_Circle_Algorithm.py
=> Adding bresenham circle program

Longest_Increasing_Subarray/Longest_Increasing_Subarray.c, Longest_Increasing_Subarray/Longest_Increasing_Subarray.cpp, Longest_Increasing_Subarray/Longest_Increasing_Subarray.go, Longest_Increasing_Subarray/Longest_Increasing_Subarray.java, Longest_Increasing_Subarray/Longest_Increasing_Subarray.py
Fixes #1149  
- Added implementation for longest Increasing subarray in C,C++, Python, Java, Go
- C
- C++
- Java
- Python
- Go
- Longest_Increasing_Subarray.py
- Longest_Increasing_Subarray.go
- Longest_Increasing_Subarray.c
- Longest_Increasing_Subarray.cpp
- Longest_Increasing_Subarray.java
=> Added Longest Increasing Subarray

Divisible_Pairs_In_Array/Divisible_Pairs_In_Array.c, Divisible_Pairs_In_Array/Divisible_Pairs_In_Array.cpp, Divisible_Pairs_In_Array/Divisible_Pairs_In_Array.go, Divisible_Pairs_In_Array/Divisible_Pairs_In_Array.java, Divisible_Pairs_In_Array/Divisible_Pairs_In_Array.py
Fixes #1175 
- Added Finding divisible pairs of an array 
- C
- C++
- Java
- Python
- Go
- Divisible_Pairs_In_Array.py
- Divisible_Pairs_In_Array.c
- Divisible_Pairs_In_Array.cpp
- Divisible_Pairs_In_Array.java
- Divisible_Pairs_In_Array.go
=> Added Divisible Pairs in an array

1-D_Array/C/Frequency_Of_A_Element.c, 1-D_Array/C/Max_And_Next_Max_Number.c, 1-D_Array/C/Mean_Variance_Standard_Deviation.c, 1-D_Array/C/Merge_Two_Sorted_Arrays.c
Fixes #1158 
- Added 1-D array folder in C
- C
- Frequency_Of_A_Element.c
- Max_And_Next_Max_Number.c 
- Mean_Variance_Standard_Deviation.c 
- Merge_Two_Sorted_Arrays.c
=> 1-D Array folder in c

1-D_Array/C++/Frequency_Of_A_Element.cpp, 1-D_Array/C++/Max_And_Next_Max_Number.cpp, 1-D_Array/C++/Mean_Variance_Standard_Deviation.cpp, 1-D_Array/C++/Merge_Two_Sorted_Arrays.cpp
Fixes #1158 
- Added 1-D array folder in C++
- C++ 
- Frequency_Of_A_Element.cpp 
- Max_And_Next_Max_Number.cpp 
- Mean_Variance_Standard_Deviation.cpp 
- Merge_Two_Sorted_Arrays.cpp
=> 1-D array folder in C++

Binary_Tree_Right_View/Binary_Tree_Right_View.cpp, Binary_Tree_Right_View/Binary_Tree_Right_View.java, Binary_Tree_Right_View/Binary_Tree_Right_View.py
Fixes #1153 
- Added Binary Tree Right View
- C++
- Java
- Python
- Binary_Tree_Right_View.cpp
- Binary_Tree_Right_View.java
- Binary_Tree_Right_View.py
=> Right View of a Binary Tree

Count_Inversion/Count_Inversion.c
Fixes #1079 
-  Added Count Inversion in c
- C
- Count_Inversion
=>  Count Inversion in c

Perfect_Number/Perfect_Number.c, Perfect_Number/Perfect_Number.cpp, Perfect_Number/Perfect_Number.go, Perfect_Number/Perfect_Number.java, Perfect_Number/Perfect_Number.py
Fixes #1159
- Added Implementation for Perfect Number in C, C++, Java, Python, Golang
- C
- C++
- Java
- Python
- Golang
- Perfect_Number.c 
- Perfect_Number.cpp
- Perfect_Number.java
- Perfect_Number.py
- Perfect_Number.go
=> Added Perfect Number

Matrix_Operations/C/Matrix_Lower_triangular.c, Matrix_Operations/C/Matrix_Multiplication.c, Matrix_Operations/C/Matrix_Sort.c, Matrix_Operations/C/Matrix_Upper_triangular.c
Fixes #1122
- Added Matrix operation in C (Matrix_Lower_triangular,Matrix_Upper_triangular,Matrix_Sort
Matrix_Multiplication)
- C
- Matrix_Lower_triangular.c
- Matrix_Multiplication.c
- Matrix_Sort.c 
- Matrix_Upper_triangular.c
=> Matrix operation in C

Nonagonal_Number/Nonagonal_Number.c, Nonagonal_Number/Nonagonal_Number.cpp, Nonagonal_Number/Nonagonal_Number.go, Nonagonal_Number/Nonagonal_Number.java, Nonagonal_Number/Nonagonal_Number.py
Fixes #1173 
- Added Nonagonal Number in 5 languages
- C
- C++
- Java
- Go
- Python
- Nonagonal_Number.py
- Nonagonal_Number.c
- Nonagonal_Number.cpp
- Nonagonal_Number.java
- Nonagonal_Number.go
Thanks!
=> Added Nonagonal Number

Longest_Alternating_Subarray/Longest_Alternating_Subarray.c, Longest_Alternating_Subarray/Longest_Alternating_Subarray.cpp, Longest_Alternating_Subarray/Longest_Alternating_Subarray.go, Longest_Alternating_Subarray/Longest_Alternating_Subarray.java, Longest_Alternating_Subarray/Longest_Alternating_Subarray.py
Fixes #1174 
- Added Longest Alternating Subarray in 5 languages
- C
- C++
- Python
- Java
- Go
- Longest_Alternating_Subarray.py
- Longest_Alternating_Subarray.c
- Longest_Alternating_Subarray.go
- Longest_Alternating_Subarray.java
- Longest_Alternating_Subarray.cpp
=> Added Longest Alternating Subarray

Mystery_Number/Mystery_Number.c, Mystery_Number/Mystery_Number.cpp, Mystery_Number/Mystery_Number.go, Mystery_Number/Mystery_Number.java, Mystery_Number/Mystery_Number.py
Fixes #1184 
- Mystery Number folder updated for runtime input
- C
- C++
- Python
- Java
- Go
- Mystery_Number.c
- Mystery_Number.cpp
- Mystery_Number.py
- Mystery_Number.java
- Mystery_Number.go
=> runtime input

Euclidean_Algorithm/Euclidean_Algorithm.kt
Fixes #1189
- Adding Euclidean_Algorithm in Kotlin
- Kotlin
- Euclidean_Algorithm.kt
Thanks!
=> Adding Euclidean Algorithm

Bubble_Sort/Bubble_Sort.kt
Fixes #1170  
- Adding Bubble_Sort in Kotlin
- Kotlin
- Bubble_Sort.kt
=> Adding Bubble_Sort

Activity_Selection/Activity_Selection.dart, Bubble_Sort/bubble_sort.dart, Heap_Sort/Heap_Sort.dart, Insertion_Sort/insertion_sort.dart, Merge_Sort/Merge_Sort.dart, Quick_Sort/Quick_Sort.dart
Fixes #490 
-  Dart sorting algorithms added 
- Dart
- Bubble_Sort.dart
- Insertion_Sort.dart
- Merge_Sort.dart
- Heap_Sort.dart
- Quick_Sort.dart
- Activity_Selection.dart
=> Bubble and insertion sort in Dart

Array_Rotation/Array_Rotation.c, Array_Rotation/Array_Rotation.cpp, Merge_Sort/Merge_Sort.cpp, Tim_Sort/Tim_Sort.c, Tim_Sort/Tim_Sort.cpp
Partly solves #1160
Fixes #1183 
- Updated files to take input at runtime
- C
- C++
- Array_Rotation.c
- Array_Rotation.cpp
- Tim_Sort.c
- Tim_Sort.cpp
- Merge_Sort.cpp
=> Updating files to take input at runtime 

Longest_Increasing_Subarray/Longest_Increasing_Subarray.c, Longest_Increasing_Subarray/Longest_Increasing_Subarray.cpp, Longest_Increasing_Subarray/Longest_Increasing_Subarray.go, Longest_Increasing_Subarray/Longest_Increasing_Subarray.java, Longest_Increasing_Subarray/Longest_Increasing_Subarray.py
Fixes #1202 
- Modified codes to allow runtime inputs.
- C
- C++
- Python
- Java
- Go
- Longest_Increasing_Subarray.java
- Longest_Increasing_Subarray.c
- Longest_Increasing_Subarray.cpp
- Longest_Increasing_Subarray.go
- Longest_Increasing_Subarray.py
=> Added runtime input

Prefix_Sum/Prefix_Sum.c, Prefix_Sum/Prefix_Sum.cpp, Prefix_Sum/Prefix_Sum.go, Prefix_Sum/Prefix_Sum.java, Prefix_Sum/Prefix_Sum.py
Fixes #1203 
- Files updated for runtime input
- C
- C++
- Java
- Go
- Python
- Prefix_Sum.c
- Prefix_Sum.cpp
- Prefix_Sum.py
- Prefix_Sum.java
- Prefix_Sum.go
=> Updated files for runtime input

Equilibrium_Index_Of_Array/Equilibrium_Index_Of_Array.c, Equilibrium_Index_Of_Array/Equilibrium_Index_Of_Array.cpp, Equilibrium_Index_Of_Array/Equilibrium_Index_Of_Array.go, Equilibrium_Index_Of_Array/Equilibrium_Index_Of_Array.java, Equilibrium_Index_Of_Array/Equilibrium_Index_Of_Array.py
Fixes #1208 
- Implementation for finding equilibrium index of an array. 
- C
- C++
- Python
- Java
- Go
- Equilibrium_Index_Of_Array.c 
- Equilibrium_Index_Of_Array.cpp
- Equilibrium_Index_Of_Array.py
- Equilibrium_Index_Of_Array.java
- Equilibrium_Index_Of_Array.go
=> Added equilibrium index of an array

Geometric_Progression/Geometric_Progression.c, Geometric_Progression/Geometric_Progression.cpp, Geometric_Progression/Geometric_Progression.go, Geometric_Progression/Geometric_Progression.java, Geometric_Progression/Geometric_Progression.py
Fixes #1200 
- Added Geometric Progression in 5 languages.
- C
- C++
- Python
- Java
- Go
- Geometric_Progression.c
- Geometric_Progression.cpp
- Geometric_Progression.py
- Geometric_Progression.java
- Geometric_Progression.go
=> Added G.P.

Perfect_Array/Perfect_Array.c, Perfect_Array/Perfect_Array.cpp, Perfect_Array/Perfect_Array.go, Perfect_Array/Perfect_Array.java, Perfect_Array/Perfect_Array.py
Fixes #1172 
- Added Perfect Array in 5 languages
- C
- C++
- Python
- Java
- Go
- Perfect_Array.py
- Perfect_Array.c
- Perfect_Array.cpp
- Perfect_Array.java
- Perfect_Array.go
=> Added Perfect Array

Rabin_Karp/Rabin_Karp.cpp
Fixes #1130 
- Added Implementation for Rabin Karp String Matching Algorithm with proper comments and 
indentation in C++ programming languages
- C++
- Rabin_Karp_String_Matching_Algo/Rabin_Karp_String_Matching.cpp
=> Added Rabin Karp String Matching in c++

Arithmetic_Progression/Arithmetic_Progression.c, Arithmetic_Progression/Arithmetic_Progression.cpp, Arithmetic_Progression/Arithmetic_Progression.go, Arithmetic_Progression/Arithmetic_Progression.java, Arithmetic_Progression/Arithmetic_Progression.py
Fixes #1199 
- Added Arithmetic Progression in 5 languages.
- C
- C++
- Java
- Python
- Go
- Arithmetic_Progression.c
- Arithmetic_Progression.cpp
- Arithmetic_Progression.py
- Arithmetic_Progression.java
- Arithmetic_Progression.go
=> Added A.P.

infix_to_prefix/Infix_To_Prefix.java, infix_to_prefix/infix_to_prefix.cpp
Fixes #990 
- added program for infix to prefix in java
- added program for infix to prefix in c++
- c++
- java
- infix_to_prefix.cpp
- infixConversion.java
-infix_to_prefix
=> Infix to prefix programs in c++ and java

Insertion_Sort/Insertion_Sort.c, Insertion_Sort/Insertion_Sort.cpp, Insertion_Sort/Insertion_Sort.go, Insertion_Sort/Insertion_Sort.java, Insertion_Sort/Insertion_Sort.py
Fixes #1225
- insertion Sort codes modified to allow runtime input
- C
- C++
- Java
- Python
- Go
- Insertion_Sort.c
- Insertion_Sort.cpp
- Insertion_Sort.java
- Insertion_Sort.py
- Insertion_Sort.go
=> Modified Insertion Sort

Selection_Sort/Selection_Sort.c, Selection_Sort/Selection_Sort.cpp, Selection_Sort/Selection_Sort.go, Selection_Sort/Selection_Sort.java, Selection_Sort/Selection_Sort.py
Fixes #1222
- Updated Selection Sort for runtime input.
- C
- C++
- Python
- Java
- Go
- Selection_Sort.c
- Selection_Sort.cpp
- Selection_Sort.py
- Selection_Sort.java
- Selection_Sort.go
=> Updated selection sort

Leaders_Of_Array/Leaders_Of_Array.c, Leaders_Of_Array/Leaders_Of_Array.cpp, Leaders_Of_Array/Leaders_Of_Array.go, Leaders_Of_Array/Leaders_Of_Array.java, Leaders_Of_Array/Leaders_Of_Array.py
Fixes #1201 
- Added implementation for finding Leaders of an array.
- C
- C++
- Java
- Python
- Go
- Leaders_Of_Array.c
- Leaders_Of_Array.cpp
- Leaders_Of_Array.py
- Leaders_Of_Array.go
- Leaders_Of_Array.java
=> Added leaders in array

Subarray_Sum/Subarray_Sum.c, Subarray_Sum/Subarray_Sum.cpp, Subarray_Sum/Subarray_Sum.go, Subarray_Sum/Subarray_Sum.java, Subarray_Sum/Subarray_Sum.py
Fixes #1197 
- Added All Subarray Sum of an array.
- C
- C++
- Python
- Java
- Go
- Subarray_Sum.c
- Subarray_Sum.cpp
- Subarray_Sum.go
- Subarray_Sum.py
- Subarray_Sum.java
=> Added subarray sum

Breadth_First_Search/Breadth_First_Search.c
Fixes #755
- Uploading BFS code in C with adjacency matrix representation
- C
- Breadth_FIrst_Search.c
=> BFS Code in C

Linear_Search/Linear_Search.c, Linear_Search/Linear_Search.cpp, Linear_Search/Linear_Search.go, Linear_Search/Linear_Search.java, Linear_Search/Linear_Search.py
Fixes #1226
- Modified Linear search codes for runtime input
- C
- C++
- Java
- Python
- Go
- Linear_Search.c
- Linear_Search.cpp
- Linear_Search.java
- Linear_Search.py
- Linear_Search.go
=> Linear search - runtime input

Naive_String_Matching/Naive_String_Matching.kt
Fixes #1228 
- Adding Naive String Matching Algorithm in Kotlin
- Kotlin
- Naive_String_Matching.kt
Thanks!
=> Naive String Matching

Logarithmic_Exponent/Logarithmic_Exponent.c, Logarithmic_Exponent/Logarithmic_Exponent.py, Modular Inverse/Modular_Inverse.cpp, Modular Inverse/Modular_Inverse.java, Modular Inverse/Modular_Inverse.py
Fixes #1244
- Modified files for runtime input
- C
- Python
- C++
- Java
- Logarithmic_Exponent.py
- Logarithmic_Exponent.c
- Modular_Inverse.py 
- Modular_Inverse.cpp
- Modular_Inverse.java
Thanks!
=> Updated files for runtime input (#1160

Gcd/gcd.py
Fixes  #1231
- gcd.py using Euclidean Algorithm
- 
- Python3
- 
- gcd/gcd.py
- 
Thanks!
=> created gcd.py using Euclidean Algorithm

Dynamic_Programming_Rod_Cutting/Dynamic_Programming_Rod_Cutting.cpp, Dynamic_Programming_Rod_Cutting/Dynamic_Programming_Rod_Cutting.go, Dynamic_Programming_Rod_Cutting/Dynamic_Programming_Rod_Cutting.java, Dynamic_Programming_Rod_Cutting/Dynamic_Programming_Rod_Cutting.py, Logarithmic_Exponent/Logarithmic_Exponent.cpp
Fixes #1243
- Updated the concerned files for runtime input
- C++
- Python
- Java
- Go
- Dynamic_Programming_Rod_Cutting.cpp 
- Dynamic_Programming_Rod_Cutting.py
- Dynamic_Programming_Rod_Cutting.go
- Dynamic_Programming_Rod_Cutting.java
- Logarithmic_Exponent.cpp
=> Modified files for runtime input (#1160)

Binary_Search/Binary_Search.cpp, Binary_Search/Binary_Search.go, Binary_Search/Binary_Search.java, Binary_Search/Binary_Search.py, Binary_Search/searching_a_circularly_sorted_array.cpp
Fixes #1224 referencing #1160 
- Added dynamic inputs and example
- C++
- Java
- Python
- Go
- Binary_Search.cpp
- Binary_Search.java
- Binary_Search.py
- Binary_Search.go
- searching_a_circularly_sorted_array.cpp
=> Modified Binary Search

Coin_Change/Coin_Change.c, Coin_Change/Coin_Change.cpp, Coin_Change/Coin_Change.go, Coin_Change/Coin_Change.java, Coin_Change/Coin_Change.py
Fixes #1241 referencing #1160 
- Added Coin Change in C
- Updated Coin Change in C++, Java, Python and Go to take dynamic inputs
- Added Problem description
- C
- C++
- Java
- Python
- Go
- Coin_Change.c
- Coin_Change.cpp
- Coin_Change.java
- Coin_Change.py
- Coin_Change.go
=> Added dynamic inputs and Coin Change program in C

Bezier_Curve/Bezier_Curve.c, Bezier_Curve/Bezier_Curve.cpp
Fixes #1028
- Added code in C and C++ for Bezier Curve
- C
- C++
- bezier_curve.c 
- bezier_curve.cpp
=> added code in C and C++ for Bezier Curve

Arithmetic_Progression/Arithmetic_Progression.c, Arithmetic_Progression/Arithmetic_Progression.cpp, Arithmetic_Progression/Arithmetic_Progression.go, Arithmetic_Progression/Arithmetic_Progression.java, Arithmetic_Progression/Arithmetic_Progression.py
Fixes #1216
- Added sum of arithmetic Progression series in C, C++, Python, Java and go
- C
- C++
- Java
- Python
- Go
- Arithmetic_Progression.c
- Arithmetic_Progression.cpp
- Arithmetic_Progression.py
- Arithmetic_Progression.java
- Arithmetic_Progression.go
=> Added Sum of A.P series

Babylonian_Method/Babylonian_Method.kt
Fixes #1168   
- Adding Babylonian_Method in Kotlin
- Kotlin
- Babylonian_Method.kt
=> Babylonian_Method in Kotlin

nCr mod P/nCr_mod_P.kt
Fixes #1205 
- nCr mod P in Kotlin
- Kotlin
- nCr_mod_P.kt 
Thanks!
=> Adding nCr_mod_p

Lucas_Theorem/Lucas_Theorem.java, Lucas_Theorem/Lucas_Theorem.py
Fixes #1081
-  Lucas Theorem in Java and Python
-  Java
- Python
- Lucas_Theorem.java
- Lucas_Theorem.py
Thanks!
=> Added Lucas theorem for Java and Python

Disjoint_Sets/Disjoint_Sets.java
Fixes #1287 
- Java implementation of Disjoint sets
- 
- Java
- 
-  Disjoint_Sets/Disjoint_Sets.java
- 
Thanks!
=> Added Java Implementation of Disjoint Sets

Arithmetic_Progression/README.md
Fixes #1305
- [x ] File names are correct.
- Added README.md for Arithmetic_Progression
- Markdown
- README.md
Thanks!
=> Added README.md for Arithmethic_Progression

Anagram/Anagram.c, Anagram/Anagram.go, Anagram/Anagram.java
Fixes #1284 
- Added Anagrams in C, Go and Java 
- C
- Java
- Go
- Anagram.c
- Anagram.java
- Anagram.go
=> Added Anagrams in C, Go and Java

Circular_Linked_List/Circular_Linked_List.java
Fixes #1285 
- [NA] Input is taken dynamically.
- Java Implementation of Circular Linked list
- 
- Java
- 
- Circular_Linked_List/Circular_Linked_List.java
- 
Thanks!
=> circular linked list-Java

Naive_String_Matching/Naive_String_Matching.cpp, Naive_String_Matching/Naive_String_Matching.java, Naive_String_Matching/Naive_String_Matching.py, Pigeonhole_Sort/Pigeonhole_Sort.java, Pigeonhole_Sort/Pigeonhole_Sort.py
Fixes #1242 referencing #1160
- Renamed files for uniformity
- Added dynamic inputs
- C++
- Java
- Python
- Naive_String_Matching.cpp
- Naive_String_Matching.java
- Naive_String_Matching.py
- Pigeonhole_Sort.java
- Pigeonhole_Sort.py
=> Added run time inputs for Naive String Matching and Pigeonhole Sort

Subset_Sum/Subset_Sum.c, Subset_Sum/Subset_Sum.go, Subset_Sum/Subset_Sum.java, Subset_Sum/Subset_Sum.py
Fixes #1270 referencing #1160 
- Updated inputs across all languages
- Added Subset Sum in C
- C
- C++
- Java
- Python
- Go
- Subset_Sum.c
- Subset_Sum.cpp
- Subset_Sum.py
- Subset_Sum.java
- Subset_Sum.go
=> Added dynamic inputs and Subset Sum in C

Geometric_Progression/Geometric_Progression.c, Geometric_Progression/Geometric_Progression.cpp, Geometric_Progression/Geometric_Progression.go, Geometric_Progression/Geometric_Progression.java, Geometric_Progression/Geometric_Progression.py
Fixes #1217 
- Added sum of Geometric Progression series in C, C++, Python, Java and go
- C
- C++
- Java
- Python
- Go
- Geometric_Progression.c
- Geometric_Progression.cpp
- Geometric_Progression.py
- Geometric_Progression.java
- Geometric_Progression.go
=> Added Sum Of G.P series

Pythagorean_Triplets/Pythagorean_Triplets.c, Pythagorean_Triplets/Pythagorean_Triplets.cpp, Pythagorean_Triplets/Pythagorean_Triplets.go, Pythagorean_Triplets/Pythagorean_Triplets.java, Pythagorean_Triplets/Pythagorean_Triplets.py
Fixes #1328 
- Added Pythagorean Triplets in 5 languages
- C
- C++
- Java
- Go
- Python
- Pythagorean_Triplets.c
- Pythagorean_Triplets.cpp
- Pythagorean_Triplets.java
- Pythagorean_Triplets.py
- Pythagorean_Triplets.go
=> Added pythagorean triplets

Nim_Game/Nim_Game.c, Nim_Game/Nim_Game.go, Nim_Game/Nim_Game.java, Nim_Game/Nim_Game.py
Fixes #1313 
- Added Nim Game implementation in C & Go
- Updated Nim Game codes in C++, Java & Python to take runtime inputs.
- C
- C++
- Java
- Python
- Go
- Nim_Game.c
- Nim_Game.cpp
- Nim_Game.java
- Nim_Game.go
- Nim_Game.py
=> Added and updated Nim Game

Rain_Water_Trapping/Rain_Water_Trapping.java, Rain_Water_Trapping/Rain_Water_Trapping.py
Fixes #808 
- adds the solution in java language for rainwater trapping problem
- changes solution of python to take dynamic input from the user
- java
- python
- Rain_Water_Trapping/Rain_Water_Trapping.java
- Rain_Water_Trapping/Rain_Water_Trapping.py
=> adds solution for rain water trapping problem in java

1-D_Array/Java/Frequency_Of_A_Element.java, 1-D_Array/Java/Max_And_Next_Max_Number.java, 1-D_Array/Java/Mean_Variance_Standard_Deviation.java, 1-D_Array/Java/Merge_Two_Sorted_Arrays.java
Fixes #1321
- Added 1-D array folder in java
- java
- Frequency_Of_A_Element.java
- Max_And_Next_Max_Number.java 
- Mean_Variance_Standard_Deviation.java 
- Merge_Two_Sorted_Arrays.java
=> Added 1d array folder in java

Next_Perfect_Square/Next_Perfect_Square.c, Next_Perfect_Square/Next_Perfect_Square.cpp, Next_Perfect_Square/Next_Perfect_Square.go, Next_Perfect_Square/Next_Perfect_Square.java, Next_Perfect_Square/Next_Perfect_Square.py
Fixes #1278 
- Added Next Perfect Square in 5 languages
- C
- C++
- Python
- Java
- Go
- Next_Perfect_Square.c
- Next_Perfect_Square.cpp
- Next_Perfect_Square.go
- Next_Perfect_Square.java
- Next_Perfect_Square.py
=> Added next perfect square

Catalan_Numbers/Catalan_Numbers.c, Catalan_Numbers/Catalan_Numbers.go
Fixes #1312 
- Added program for Catalan numbers in C and Go 
- C
- Go
- Catalan_Numbers.c
- Catalan_Numbers.go
=> Catalan Numbers in C and Go

Sum_Of_Cubes/Sum_Of_Cubes.c, Sum_Of_Cubes/Sum_Of_Cubes.cpp, Sum_Of_Cubes/Sum_Of_Cubes.go, Sum_Of_Cubes/Sum_Of_Cubes.java, Sum_Of_Cubes/Sum_Of_Cubes.py
Fixes #1274 
- Added program for sum of cubes of first N natural numbers
- C
- C++
- Java
- Python
- Go
- Sum_Of_Cubes.c
- Sum_Of_Cubes.cpp
- Sum_Of_Cubes.java
- Sum_Of_Cubes.py
- Sum_Of_Cubes.go
=> Sum of Cubes of first N natural numbers

Sum_Of_Squares/Sum_O_Squares.go, Sum_Of_Squares/Sum_Of_Squares.c, Sum_Of_Squares/Sum_Of_Squares.cpp, Sum_Of_Squares/Sum_Of_Squares.java, Sum_Of_Squares/Sum_Of_Squares.py
Fixes #1273 
- Added program for sum of squares of first N natural numbers
- C
- C++
- Java
- Python
- Go
- Sum_Of_Squares.c
- Sum_Of_Squares.cpp
- Sum_Of_Squares.java
- Sum_Of_Squares.py
- Sum_Of_Squares.go
=> Sum of squares of first N natural numbers

Sum_Of_Digits/Sum_Of_Digits.c, Sum_Of_Digits/Sum_Of_Digits.cpp, Sum_Of_Digits/Sum_Of_Digits.go, Sum_Of_Digits/Sum_Of_Digits.java, Sum_Of_Digits/Sum_Of_Digits.py
Fixes #1331 
- Added Sum of digits of a number in C, C++, Java, Python and Go
- C
- C++
- Java
- Python
-Go
- Sum_Of_Digits.c
- Sum_Of_Digits.cpp
- Sum_Of_Digits.java
- Sum_Of_Digits.py
- Sum_Of_Digits.go
=> Sum of Digits of a number

Reverse_Of_Number/Reverse_Of_Number.c, Reverse_Of_Number/Reverse_Of_Number.cpp, Reverse_Of_Number/Reverse_Of_Number.go, Reverse_Of_Number/Reverse_Of_Number.java, Reverse_Of_Number/Reverse_Of_Number.py
Fixes #1330 
- Added implementation for reversing a number in C, C++, Java, Python and Go 
- C
- C++
- Java
- Python
- Go
- Reverse_Of_Number.c
- Reverse_Of_Number.cpp
- Reverse_Of_Number.java
- Reverse_Of_Number.py
- Reverse_Of_Number.go
=> Reverse of a number

Digit_Count/Digit_Count.c, Digit_Count/Digit_Count.cpp, Digit_Count/Digit_Count.go, Digit_Count/Digit_Count.java, Digit_Count/Digit_Count.py
Fixes #1337 
- Added Frequency of digits (digit count) of a number in 5 languages.
- C
- C++
- Python
- Java
- Go
- Digit_Count.c
- Digit_Count.cpp
- Digit_Count.go
- Digit_Count.py
- Digit_Count.java
=> Added digit count

Tribonacci_Numbers/Tribonacci_Numbers.c, Tribonacci_Numbers/Tribonacci_Numbers.cpp, Tribonacci_Numbers/Tribonacci_Numbers.go, Tribonacci_Numbers/Tribonacci_Numbers.java, Tribonacci_Numbers/Tribonacci_Numbers.py
Fixes #1338 
- Added Tribonacci numbers in 5 languages
- C
- C++
- Java
- Python
- Go
- Tribonacci_Numbers.c
- Tribonacci_Numbers.cpp
- Tribonacci_Numbers.java
- Tribonacci_Numbers.go
- Tribonacci_Numbers.py
=> Added Tribonacci Numbers

Power_Of_Two/Power_Of_Two.c, Power_Of_Two/Power_Of_Two.cpp, Power_Of_Two/Power_Of_Two.go, Power_Of_Two/Power_Of_Two.java, Power_Of_Two/Power_Of_Two.py
Fixes #1344 
- Added implementations for checking whether a number is a power of two or not
- C
- C++
- Java
- Python
- Go
- Power_Of_Two.c
- Power_Of_Two.cpp
- Power_Of_Two.java
- Power_Of_Two.py
- Power_Of_Two.go
=> Check for Power of Two

Natural_Numbers_Sum/Natural_Numbers_Sum.c, Natural_Numbers_Sum/Natural_Numbers_Sum.cpp, Natural_Numbers_Sum/Natural_Numbers_Sum.go, Natural_Numbers_Sum/Natural_Numbers_Sum.java, Natural_Numbers_Sum/Natural_Numbers_Sum.py
Fixes #1272 
- Added implementation for finding sum of first N natural numbers in 5 languages
- C
- C++
- Python
- Java
- Go
- Sum_of_N_Natural_Numbers.c
- Sum_of_N_Natural_Numbers.cpp
- Sum_of_N_Natural_Numbers.go
- Sum_of_N_Natural_Numbers.java
- Sum_of_N_Natural_Numbers.py
=> Added Sum of N Natural Numbers

Number_Conversion/Java/Hexadecimal_To_Binary.java, Number_Conversion/Java/Hexadecimal_To_Decimal.java, Number_Conversion/Java/Octal_To_Decimal.java, Number_Conversion/Python/Octal_To_Decimal.py
Fixes #1357
- Number conversion in java and python 
- java
- python
- Hexadecimal_To_Binary.java
- Hexadecimal_To_Decimal.java
- Octal_To_Decimal.java
- Octal_To_Decimal.py
=> added Number Conversion

Sum_Of_Cubes/Sum_Of_Cubes.js
Fixes #1274 
- Added program for sum of cubes of first N natural Numbers.
- JavaScript
- Sum_Of_Cubes.js
=> Add code for Cubes of N numbers in JavaScript.

Simple_Interest/Simple_Interest.c, Simple_Interest/Simple_Interest.cpp, Simple_Interest/Simple_Interest.go, Simple_Interest/Simple_Interest.java, Simple_Interest/Simple_Interest.py
Fixes #1368
- Added Simple Interest program in 5 languages.
- C
- C++
- Python
- Java
- Go
- Simple_Interest.c
- Simple_Interest.cpp
- Simple_Interest.py
- Simple_Interest.java
- Simple_Interest.go
=> Added Simple Interest

Tribonacci_Numbers/Tribonacci_Numbers_DP.c, Tribonacci_Numbers/Tribonacci_Numbers_DP.cpp, Tribonacci_Numbers/Tribonacci_Numbers_DP.go, Tribonacci_Numbers/Tribonacci_Numbers_DP.java, Tribonacci_Numbers/Tribonacci_Numbers_DP.py
Fixes #1366
- Added Tribonacci Numbers using DP
- C
- C++
- Python
- Java
- Go
- Tribonacci_Numbers_DP.c
- Tribonacci_Numbers_DP.cpp
- Tribonacci_Numbers_DP.py
- Tribonacci_Numbers_DP.java
- Tribonacci_Numbers_DP.py
=> Added tribonacci numbers using DP

RSA_CRT/RSA_CRT.py
Fixes #1323 
- Decryption of RSA using CRT added. 
- Python
- RSA_CRT.py
Thanks!
=> Decrypting RSA using Chinese Remainder Theorem

Centered_Decagonal_Number/Centered_Decagonal_Number.c, Centered_Decagonal_Number/Centered_Decagonal_Number.cpp, Centered_Decagonal_Number/Centered_Decagonal_Number.go, Centered_Decagonal_Number/Centered_Decagonal_Number.java, Centered_Decagonal_Number/Centered_Decagonal_Number.py
Fixes #1361
- Centered Decagonal Numbers in C, C++, Java, Python and go 
- C++
- java 
- go
- python
- C
- Centered_Decagonal_Number.c
- Centered_Decagonal_Number.cpp
- Centered_Decagonal_Number.java
- Centered_Decagonal_Number.go
- Centered_Decagonal_Number.py
=> Added Centered Decagonal Number

Fibonacci_Words/Fibonacci_Words.c, Fibonacci_Words/Fibonacci_Words.cpp, Fibonacci_Words/Fibonacci_Words.go, Fibonacci_Words/Fibonacci_Words.java, Fibonacci_Words/Fibonacci_Words.py
Fixes #1347 
- Added Fibonacci Words
- C
- C++
- Java
- Python
- Go
- Fibonacci_Words.c
- Fibonacci_Words.cpp
- Fibonacci_Words.go
- Fibonacci_Words.java
- Fibonacci_Words.py
=> Added fibonacci words

Coprime_Numbers/Coprime_Numbers.c, Coprime_Numbers/Coprime_Numbers.cpp, Coprime_Numbers/Coprime_Numbers.go, Coprime_Numbers/Coprime_Numbers.java, Coprime_Numbers/Coprime_Numbers.py
Fixes #1343
- Added implementation for checking coprime numbers 
- C
- C++
- Java
- Python
- Go
- Coprime_Numbers.c
- Coprime_Numbers.cpp
- Coprime_Numbers.java
- Coprime_Numbers.py
-  Coprime_Numbers.go
=> Implementation for Coprime Numbers

Binary_Heap/BinaryHeap.py, Binary_Heap/README.md
Fixes #1117 #469 
- Binary Heap Implementation in python
- Binary Heap README
- Python
- BinaryHeap.py
- README.md
=> Binary Heap Implementation in python  with README #gssoc19 #1117 #469

Number_Conversion/C++/Binary_To_Decimal.cpp, Number_Conversion/C++/Decimal_To_Hexadecimal.cpp, Number_Conversion/C++/Decimal_To_Octal.cpp, Number_Conversion/C/Binary_To_Decimal.c, Number_Conversion/C/Decimal_To_Hexadecimal.c, Number_Conversion/C/Decimal_To_Octal.c
Fixes #1326
- Number conversion in C and C++ 
- C
- C++
- Binary_To_Decimal.cpp
- Decimal_To_Octal.cpp 
- Decimal_To_Hexadecimal.cpp
- Binary_To_Decimal.c 
- Decimal_To_Octal.c
- Decimal_To_Hexadecimal.c
=> Number conversion

Number_Conversion/C++/Hexadecimal_To_Binary.cpp, Number_Conversion/C++/Hexadecimal_To_Decimal.cpp, Number_Conversion/C++/Octal_To_Decimal.cpp, Number_Conversion/C/Hexadecimal_To_Binary.c, Number_Conversion/C/Hexadecimal_To_Decimal.c, Number_Conversion/C/Octal_To_Decimal.c
Fixes #1327
- Number conversion in C and C++ 
- C
- C++
- Hexadecimal_To_Binary.cpp
- Hexadecimal_To_Decimal.cpp 
- Octal_To_Decimal.cpp
- Hexadecimal_To_Binary.c
- Hexadecimal_To_Decimal.c
- Octal_To_Decimal.c
=> Number_Conversion

Tribonacci_Words/Tribonacci_Words.c, Tribonacci_Words/Tribonacci_Words.cpp, Tribonacci_Words/Tribonacci_Words.go, Tribonacci_Words/Tribonacci_Words.java, Tribonacci_Words/Tribonacci_Words.py
Fixes #1348 
- Added Tribonacci Words in 5 languages
- C
- C++
- Java
- Python
- Go
- Tribonacci_Words.c 
- Tribonacci_Words.cpp
- Tribonacci_Words.py
- Tribonacci_Words.java
- Tribonacci_Words.go
=> Added Tribonacci Words

Decagonal_Numbers/Decagonal_Numbers.c, Decagonal_Numbers/Decagonal_Numbers.cpp, Decagonal_Numbers/Decagonal_Numbers.go, Decagonal_Numbers/Decagonal_Numbers.java, Decagonal_Numbers/Decagonal_Numbers.py
Fixes #1346
- Decagonal Numbers in C, C++, Java, Python and go 
- C++
- java 
- go
- python
- C
- Decagonal_Numbers.c
- Decagonal_Numbers.cpp
- Decagonal_Numbers.java
- Decagonal_Numbers.go
- Decagonal_Numbers.py
=> Decagonal_Numbers

Geometric_Progression/Sum_Of_Infinite_GP.c, Geometric_Progression/Sum_Of_Infinite_GP.cpp, Geometric_Progression/Sum_Of_Infinite_GP.go, Geometric_Progression/Sum_Of_Infinite_GP.java, Geometric_Progression/Sum_Of_Infinite_GP.py
Fixes #1299 
- Added implementation for infinite sum gp in 5 languages
- C
- C++
- Python
- Go
- Java
- Sum_Of_Infinite_GP.c 
- Sum_Of_Infinite_GP.cpp
- Sum_Of_Infinite_GP.py
- Sum_Of_Infinite_GP.go
- Sum_Of_Infinite_GP.java
=> Added infinite sum of gp

Selection_Algorithm_Repo/README.md, Selection_Algorithm_Repo/Selection_algo_using_Quick_sort.c, Selection_Algorithm_Repo/Selection_algo_using_Quick_sort.cpp
Fixes #1245 
- Implementation of Select kth Smallest Element Using QuickSort in C, C++, README files.
- C
- C++
-  Selection_Algorithm_Repo/README.md 
-  Selection_Algorithm_Repo/Selection_algo_using_Quick_sort.c 
-  Selection_Algorithm_Repo/Selection_algo_using_Quick_sort.cpp
=> Added Selection Algorithm Using Quick sort in C, C++, README.md

Good_Permutation/Good_Permutation.c, Good_Permutation/Good_Permutation.cpp, Good_Permutation/Good_Permutation.go, Good_Permutation/Good_Permutation.java, Good_Permutation/Good_Permutation.py
Fixes #1297
- Added implementation for Good permutation in 5 languages
- C
- C++
- Python
- Java
- Go
- Good_Permutation.c
- Good_Permutation.cpp
- Good_Permutation.py
- Good_Permutation.java
- Good_Permutation.go
=> Added good permutation

Majority_Element/Majority_Element.c, Majority_Element/Majority_Element.cpp, Majority_Element/Majority_Element.go, Majority_Element/Majority_Element.java, Majority_Element/Majority_Element.py
Fixes #1367 
- Added implementation for finding majority element of an array
- C
- C++
- Java
- Python
- Go
- Majority_Element.c
- Majority_Element.cpp
- Majority_Element.java
- Majority_Element.py
- Majority_Element.go
=> Majority Element of an Array

Square_Root_Decomposition/SquareRootDecomposition.java
Fixes #1351 
- Square Root Decomposition in Java
-  Java
- SquareRootDecomposition.java
Thanks!
=> Square Root Decomposition in Java

Bubble_Sort/Bubble_Sort.c, Bubble_Sort/Bubble_Sort.cpp, Counting_Sort/Counting_Sort.c, Counting_Sort/Counting_Sort.cpp, Heap_Sort/Heap_Sort.c, Heap_Sort/Heap_Sort.cpp
Partly solves #1160 
Fixes #1179 
- Updated files to take input at runtime
- C
- C++
- Bubble_Sort.c 
- Bubble_Sort.cpp
- Counting_Sort.c
- Counting_Sort.cpp
- Heap_Sort.c
- Heap_Sort.cpp
=> Updated files to take input at runtime

Fibonacci_Number/Fibonacci_Number.c, Fibonacci_Number/Fibonacci_Number.cpp, Fibonacci_Number/Fibonacci_Number.go, Fibonacci_Number/Fibonacci_Number.java, Fibonacci_Number/Fibonacci_Number.py
Fixes #1259
- Added Fibonacci numbers and Fibonacci series in C, C++, Java, Python and go
- C
- C++
- python
- java
- go
- Fibonacci_Number.c
- Fibonacci_Number.cpp
- Fibonacci_Number.java
- Fibonacci_Number.py
- Fibonacci_Number.go
=> Added Fibonacci number and Fibonacci series

Perfect_Square_String/Perfect_Square_String.c, Perfect_Square_String/Perfect_Square_String.cpp, Perfect_Square_String/Perfect_Square_String.go, Perfect_Square_String/Perfect_Square_String.java, Perfect_Square_String/Perfect_Square_String.py
Fixes #1280
- Added Perfect Square String in c, c++, Java, python and go
- C
- C++
- java 
- python
- go
- Perfect_Square_String.c 
- Perfect_Square_String.cpp
- Perfect_Square_String.go
- Perfect_Square_String.java
- Perfect_Square_String.py
=> Added Perfect Square String

Prime_Number/Prime_Number.c, Prime_Number/Prime_Number.cpp, Prime_Number/Prime_Number.go, Prime_Number/Prime_Number.java, Prime_Number/Prime_Number.py
Fixes #1182
- Added Prime Number using recursion in c, c++, python, go and java
- C
- C++
- Go
- python
- java
- Prime_Number.c 
- Prime_Number.cpp 
- Prime_Number.py
- Prime_Number.java
- Prime_Number.go
=> Added Prime Number using recursion

Binary_Heap/Binary_Heap.java
Fixes #1303 
- 
- 
- Java
- 
- Binary_Heap.java
- 
Thanks!
=> Binary heap java

Doubly_Linked_List/Doubly_linked_list.rb
Fixes #1271 
- [] Input is taken dynamically.
- Implemented Doubly linked list in ruby language.
- ruby
- Doubly_linked_list.rb
Thanks!
=> Doubly_linked _list

Dearrangements/Dearrangements.c, Dearrangements/Dearrangements.cpp, Dearrangements/Dearrangements.go, Dearrangements/Dearrangements.java, Dearrangements/Dearrangements.py
Fixes #1382 
- Added implementation for counting dearrangements.
- C
- C++
- Go
- Python
- Java
- Dearrangements.c
- Dearrangements.cpp
- Dearrangements.java
- Dearrangements.go
- Dearrangements.py
=> Added Dearrangements

Leap_Year/Leap_Year.c, Leap_Year/Leap_Year.cpp, Leap_Year/Leap_Year.go, Leap_Year/Leap_Year.java, Leap_Year/Leap_Year.py
Fixes #1365 
- Added implementation for finding all leap years between any two years 
- C
- C++
- Java
- Python
- Go
- Leap_Year.c
- Leap_Year.cpp
- Leap_Year.java
- Leap_Year.py
- Leap_Year.go
=> Find all leap years occuring between any two years

Compound_Interest/Compound_Interest.c, Compound_Interest/Compound_Interest.cpp, Compound_Interest/Compound_Interest.go, Compound_Interest/Compound_Interest.java, Compound_Interest/Compound_Interest.py
Fixes #1373
- Added Compound Interest in C, C++, Java, Python, Go
- C
- C++
- java
- go
- python
- Compound_Interest.c 
- Compound_Interest.cpp
- Compound_Interest.py
- Compound_Interest.go
- Compound_Interest.java
=> Added Compound Interest

Distance_Between_Points/Distance_Between_Points.c, Distance_Between_Points/Distance_Between_Points.cpp, Distance_Between_Points/Distance_Between_Points.go, Distance_Between_Points/Distance_Between_Points.java, Distance_Between_Points/Distance_Between_Points.py
Fixes #1378 
- Added Implementation for distance between coordinates in 2d plane
- C
- C++
- Python
- Go
- Java
- Distance_Between_Points.c
- Distance_Between_Points.cpp
- Distance_Between_Points.go
- Distance_Between_Points.java
- Distance_Between_Points.py
=> Added Distance Between Points

Delannoy_Number/Delannoy_Number.c, Delannoy_Number/Delannoy_Number.cpp, Delannoy_Number/Delannoy_Number.go, Delannoy_Number/Delannoy_Number.java, Delannoy_Number/Delannoy_Number.py
Fixes #1406
- Added Delannoy Number Implementation.
- C
- C++
- Python
- Java
- Go
- Delannoy_Number.c
- Delannoy_Number.cpp
- Delannoy_Number.go
- Delannoy_Number.java
- Delannoy_Number.py
=> Added Delannoy Number

Centered_Square_Number/Centered_Square_Number.c, Centered_Square_Number/Centered_Square_Number.cpp, Centered_Square_Number/Centered_Square_Number.go, Centered_Square_Number/Centered_Square_Number.java, Centered_Square_Number/Centered_Square_Number.py
Fixes #1370
- Centered Square Number in C, C++, Java, Python and go
- C
- C++
- java
- go 
- python
- Centered_Square_Number.c
- Centered_Square_Number.cpp
- Centered_Square_Number.java
- Centered_Square_Number.go
- Centered_Square_Number.py
=> Added Centered Square Number

Partition_Problem/Partition_Problem.c, Partition_Problem/Partition_Problem.cpp, Partition_Problem/Partition_Problem.go, Partition_Problem/Partition_Problem.java, Partition_Problem/Partition_Problem.py
Fixes #1402
- Added Partition Problem
- C
- C++
- Java
- Python
- Go
- Partition_Problem.c
- Partition_Problem.cpp
- Partition_Problem.go
- Partition_Problem.py
- Partition_Problem.java
=> Added Partition Problem

Dearrangements/Dearrangements_DP.c, Dearrangements/Dearrangements_DP.cpp, Dearrangements/Dearrangements_DP.go, Dearrangements/Dearrangements_DP.java, Dearrangements/Dearrangements_DP.py
Fixes #1400 
- Added Dearrangements using Dynamic Programming
- C
- C++
- Java
- Python
- Go
- Dearrangements_DP.c 
- Dearrangements_DP.cpp
- Dearrangements_DP.java
- Dearrangements_DP.go
- Dearrangements_DP.py
=> Added Dearrangements using DP

Manhattan_Distance/Manhattan_Distance.c, Manhattan_Distance/Manhattan_Distance.cpp, Manhattan_Distance/Manhattan_Distance.go, Manhattan_Distance/Manhattan_Distance.java, Manhattan_Distance/Manhattan_Distance.py
Fixes #1377 
- Added Manhattan Distance in 5 languages
- C
- C++
- Python
- Go
- Java
- Manhattan_Distance.c
- Manhattan_Distance.cpp
- Manhattan_Distance.py
- Manhattan_Distance.go
- Manhattan_Distance.java
=> Added Manhattan Distance

Special_Permutation/Special_Permutation.c, Special_Permutation/Special_Permutation.cpp, Special_Permutation/Special_Permutation.go, Special_Permutation/Special_Permutation.java, Special_Permutation/Special_Permutation.py
Fixes #1405 
- Added Implementation for Special Permutation
- C
- C++
- Java
- Python
- Go
- Special_Permutation.c 
- Special_Permutation.cpp
- Special_Permutation.go
- Special_Permutation.java
- Special_Permutation.py
=> Added Special Permutation

Cyclic_Permutation/Cyclic_Permutation.c, Cyclic_Permutation/Cyclic_Permutation.cpp, Cyclic_Permutation/Cyclic_Permutation.go, Cyclic_Permutation/Cyclic_Permutation.java, Cyclic_Permutation/Cyclic_Permutation.py
Fixes #1298
- Added Implementation for cyclic permutation of a number in 5 languages
- C
- C++
- Java
- Python
- Go
- Cyclic_Permutation.c
- Cyclic_Permutation.cpp
- Cyclic_Permutation.py
- Cyclic_Permutation.java
- Cyclic_Permutation.go
=> Added Cyclic Permutation

1-D_Array/Python/Frequency_Of_A_Element.py, 1-D_Array/Python/Max_And_Next_Max_Number.py, 1-D_Array/Python/Mean_Variance_Standard_Deviation.py, 1-D_Array/Python/Merge_Two_Sorted_Arrays.py
Fixes #1320 
- 1-d array in python added
- python
- Frequency_Of_A_Element.py
- Max_And_Next_Max_Number.py
- Mean_Variance_Standard_Deviation.py
- Merge_Two_Sorted_Arrays.py
=> 1-D array in Python added

Rotation_Of_Numbers/Rotation_Of_Numbers.c, Rotation_Of_Numbers/Rotation_Of_Numbers.cpp, Rotation_Of_Numbers/Rotation_Of_Numbers.java, Rotation_Of_Numbers/Rotation_Of_Numbers.py
Fixes #1421 
- Added Rotation Of Numbers
- C
- C++
- Java
- Python
- Rotation_Of_Numbers.c 
- Rotation_Of_Numbers.cpp
- Rotation_Of_Numbers.java
- Rotation_Of_Numbers.py
=> Added Rotation Of Numbers

Assembly_Line_Scheduling/Assembly_Line_Scheduling.php, Assembly_Line_Scheduling/Assembly_Line_Scheduling.py
Fixes 774 (Already Referred by [PR-1254](https://github.com/jainaman224/Algo_Ds_Notes/pull/1254))
- Added Implementation of Assembly Line Scheduling
- Php
- Python
- Assembly_Line_Scheduling/Assembly_Line_Scheduling.php
- Assembly_Line_Scheduling/Assembly_Line_Scheduling.py
Thanks!
=> Assembly Line Scheduling : PHP and Python added

Lucas_Numbers/Lucas_Number.c, Lucas_Numbers/Lucas_Number.cpp, Lucas_Numbers/Lucas_Number.go, Lucas_Numbers/Lucas_Number.java, Lucas_Numbers/Lucas_Number.py
Fixes #1420 
- Added Lucas number implementation in 5 languages.
- C
- C++
- Java
- Go
- Python
- Lucas_Numbers.c
- Lucas_Numbers.cpp
- Lucas_Numbers.py
- Lucas_Numbers.java
- Lucas_Numbers.go
=> Added Lucas Numbers

Kruskal_Algorithm/README.md
Fixes #1318
- [x ] File names are correct.
- Added README.md for Kruskal Algorithm
- Markdown
- README.md
Thanks!
=> Added README.md for Kruskal Algorithm

Circular_Queue/Circular_Queue.c, Circular_Queue/Circular_Queue.cpp
Fixes #1264
- Added Circular_Queue in c and c++
- C
- C++
- Circular_Queue.c
- Circular_Queue.cpp
=> Added Circular_Queue

Celebrity_Problem/Celebrity_Problem.c, Celebrity_Problem/Celebrity_Problem.cpp, Celebrity_Problem/Celebrity_Problem.go, Celebrity_Problem/Celebrity_Problem.java, Celebrity_Problem/Celebrity_Problem.py
Fixes #1401 
- Added Celebrity Problem in 5 languages.
- C
- C++
- Java
- Python
- Go
- Celebrity_Problem.c
- Celebrity_Problem.cpp
- Celebrity_Problem.java
- Celebrity_Problem.py
- Celebrity_Problem.go
=> Added Celebrity Problem

Skip_list/README.md, Skip_list/skip_list.cpp
Fixes #1413
- Skip list added 
- C++
- Skip_list/skip_list.cpp
Thanks!
=> skip list added in c++

Bitonic_Point/Bitonic_Point.c, Bitonic_Point/Bitonic_Point.cpp, Bitonic_Point/Bitonic_Point.go, Bitonic_Point/Bitonic_Point.java, Bitonic_Point/Bitonic_Point.py
Fixes #1419 
- Added Bitonic Point implementation
- C
- C++
- Python
- Go
- Java
- Bitonic_Point.c
- Bitonic_Point.cpp
- Bitonic_Point.go
- Bitonic_Point.java
- Bitonic_Point.py
=> Added Bitonic Point

Power_Set/Power_Set.c, Power_Set/Power_Set.cpp, Power_Set/Power_Set.go, Power_Set/Power_Set.java, Power_Set/Power_Set.py
Fixes #1429 
- Added Power Set in 5 languages.
- C
- C++
- Java
- Python
- Go
- Power_Set.c
- Power_Set.cpp
- Power_Set.go
- Power_Set.py
- Power_Set.java
=> Added Power Set

Root_Mean_Square/Root_Mean_Square.c, Root_Mean_Square/Root_Mean_Square.cpp, Root_Mean_Square/Root_Mean_Square.go, Root_Mean_Square/Root_Mean_Square.java, Root_Mean_Square/Root_Mean_Square.py
Fixes #1430 
- Added Implementation for RMS
- C
- C++
- Python
- Go
- Java
- Root_Mean_Square.c
- Root_Mean_Square.cpp
- Root_Mean_Square.py
- Root_Mean_Square.go
- Root_Mean_Square.java
=> Added Root Mean Square

Markov_Matrix/Markov_Matrix.c, Markov_Matrix/Markov_Matrix.cpp, Markov_Matrix/Markov_Matrix.java, Markov_Matrix/Markov_Matrix.py
Fixes #1442
- Added Markov Matrix
- C
- C++
- Java
- Python
- Markov_Matrix.c
- Markov_Matrix.cpp
- Markov_Matrix.java
- Markov_Matrix.py
=> Added Markov Matrix

Jolly_Jumper_Sequence/Jolly_Jumper_Sequence.c, Jolly_Jumper_Sequence/Jolly_Jumper_Sequence.cpp, Jolly_Jumper_Sequence/Jolly_Jumper_Sequence.go, Jolly_Jumper_Sequence/Jolly_Jumper_Sequence.java, Jolly_Jumper_Sequence/Jolly_Jumper_Sequence.py
Fixes #1418 
- Added Implementation of Jolly Jumper Sequence.
- C
- C++
- Java
- Go
- Python
- Jolly_Jumper_Sequence.c
- Jolly_Jumper_Sequence.cpp
- Jolly_Jumper_Sequence.py
- Jolly_Jumper_Sequence.go
- Jolly_Jumper_Sequence.java
=> Added Jolly Jumper Sequence

Set_Bits_Till_N/Set_Bits_Till_N.c, Set_Bits_Till_N/Set_Bits_Till_N.cpp, Set_Bits_Till_N/Set_Bits_Till_N.go, Set_Bits_Till_N/Set_Bits_Till_N.java, Set_Bits_Till_N/Set_Bits_Till_N.py
Fixes #1451 
- Added implementation for finding total number of set bits till N.
- C
- C++
- Python
-  Java
- Go
- Set_Bits_Till_N.c
- Set_Bits_Till_N.cpp
- Set_Bits_Till_N.go
- Set_Bits_Till_N.java
- Set_Bits_Till_N.go
=> Added Count of set bits till N

Matrix_Operations/Total_Possible_Paths/Total_Possible_Paths.c, Matrix_Operations/Total_Possible_Paths/Total_Possible_Paths.cpp, Matrix_Operations/Total_Possible_Paths/Total_Possible_Paths.go, Matrix_Operations/Total_Possible_Paths/Total_Possible_Paths.java, Matrix_Operations/Total_Possible_Paths/Total_Possible_Paths.py
Fixes #1452 
- Added Implementation for finding total possible paths from (0,0) to (m,n) in a 2d Matrix.
- C
- C++
- Java
- Python
- Go
- Total_Possible_Paths.c
- Total_Possible_Paths.cpp
- Total_Possible_Paths.py
- Total_Possible_Paths.java
- Total_Possible_Paths.go
=> Added Total possible paths in 2D matrix

Assembly_Line_Scheduling/Assembly_Line_Scheduling.c, Assembly_Line_Scheduling/Assembly_Line_Scheduling.cpp, Assembly_Line_Scheduling/Assembly_Line_Scheduling.cs, Assembly_Line_Scheduling/Assembly_Line_Scheduling.java
Fixes #774 
- Added Implementation of Assembly Line Scheduling
- C
- C++
- C#
- Java
- Assembly_Line_Scheduling/Assembly_Line_Scheduling.c
- Assembly_Line_Scheduling/Assembly_Line_Scheduling.cpp
- Assembly_Line_Scheduling/Assembly_Line_Scheduling.cs
- Assembly_Line_Scheduling/Assembly_Line_Scheduling.java
Thanks!
=> Assembly Line Scheduling

Armstrong_Number/README.md
Fixes #1439
- Added README.md for Armstrong Number
- Markdown
- README.md
Thanks!
=> Added README.md for Armstrong Number

Perfect_Sum/Perfect_Sum.c, Perfect_Sum/Perfect_Sum.cpp, Perfect_Sum/Perfect_Sum.go, Perfect_Sum/Perfect_Sum.java, Perfect_Sum/Perfect_Sum.py
Fixes #1470 
- Added programs for printing all subsets with given sum 
- C
- C++
- Java
- Python
- Go 
- Perfect_Sum.c
- Perfect_Sum.cpp
- Perfect_Sum.py
- Perfect_Sum.go
- Perfect_Sum.java
=> Added Perfect Sum Problem

Liang_Barsky_Algo/Liang_Barsky_Algo.c, Liang_Barsky_Algo/Liang_Barsky_Algo.cpp
Fixes #1229
- A new algorithm of line clipping has been added named liang barsky algo.
- c
- c++
- liangBarskyAlgo.c
- liangBarskyAlgo.cpp
Thanks!
=> Liang barsky algo

Bitonic_Array/Bitonic_Array.c, Bitonic_Array/Bitonic_Array.cpp, Bitonic_Array/Bitonic_Array.go, Bitonic_Array/Bitonic_Array.java, Bitonic_Array/Bitonic_Array.py
Fixes #1432 
- Added implementation to check if an array is Bitonic or not
- C
- C++
- Java
- Python
- Go
- Bitonic_Array.c
- Bitonic_Array.cpp
- Bitonic_Array.java
- Bitonic_Array.go
- Bitonic_Array.py
=> Added program to check whether an array is bitonic or not

Expression_Tree/Expression_Tree.cpp, Expression_Tree/Expression_Tree.py
Fixes #1132 
-  add Expression tree code
-  c++
-  python
-  Expression_Tree.cpp
-  Expression_Tree.py
Thanks!
=> Expression tree

Bitonic_Point/Bitonic_Point.rb
Fixes #1459 
- Implemented bitonic point algorithm in ruby language.
- Ruby
- Bitonic_Point.rb
Thanks!
=> Bitonic point

Nobel_Integer/Noble_Integer.c, Nobel_Integer/Noble_Integer.cpp, Nobel_Integer/Noble_Integer.java, Nobel_Integer/Noble_Integer.py
Fixes #1437 
- Noble Integer code implemented in c, cpp, java and python .
- C
- C++
- Java
- Python
- Noble_Integer.c
- Noble_Integer.cpp
- Noble_Integer.java
- Noble_Integer.py
Thanks!
=> Noble Integer implementation in C, C++, Java and Python added

Prime_Number/Prime_Number.js
Fixes #1567  
- The Prime Numbers folder had no implementation in JavaScript so added the necessary script.
- JavaScript
- New File added to Prime_Numbers folder 
Thanks!
=> Added Implementation of Prime Numbers using JS

Sum_Of_Digits/Sum_Of_Digits.kt
Fixes # 1483
- Sum_Of_Digits in Kotlin
- Kotlin
- Sum_Of_Digits.kt
Thanks!
=> Sum_Of_Digits in Kotlin

Digit_Count/Digit_Count.kt, Sum_Of_Digits/Sum_Of_Digits.kt
Fixes # 1485
- Digit_Count in Kotlin
- Kotlin
- Digit_Count.kt
Thanks!
=> Digit count

Sum_Of_Squares/Sum_Of_Squares.kt
Fixes # 1487
- Sum_Of_Squares in Kotlin
- Kotlin
- Sum_Of_Squares.kt
Thanks!
=> Sum_Of_Squares in Kotlin

Cycle_Sort/Cycle_Sort.cs
Fixes #1672 
- added cycle sort program in C#
- 
- C#
- 
- Cycle_Sort.cs
- 
Thanks!
=> Added Cyclesort in C#

Array_Rotation/Array_Rotation.java
Fixes #
- I have added a rightRotate() method that rotates the array to its right by d elements
- java
- None
Thanks!
I have updated this code for the issue #1762
=> Updated Array_Rotation 

Merge_Sort/Merge_Sort.java, Merge_Sort/Merge_sort.cs
Fixes #1630 
- Implementation of Merge Sort
- C#
- Merge_sort.cs
Thanks!
=> Added Merge Sort in C#

Chinese_Remainder_Theorem/Chinese_Remainder_Theorem.js
Fixes #1878 
- The Implementation of CRT commonly known as Chinese Remainder Theorem in JavaScript.
- JavaScript
- Addition of file named Chinese_Remainder_Theorem.js inside the Chinese_Remainder_Theorem folder.
Thanks!
=> Added Implementation of CRT in JavaScript

Cycle_Sort/Cycle_Sort.cs
Fixes #1672 
- Added Cycle-sort-in C#
- 
- C#
- 
- Cycle_sort.cs
- 
Thanks!
=> Cycle sort in c#

Armstrong_Number/ArmstrongNumber.go
Fixes #1624 
- Add Golang implementation of Armstrong Number
- 
- Golang
- 
- ArmstrongNumber.GO
- 
Thanks!
=> add Armstrong Number code in Golang

Egg_Drop/Egg_drop.cs
Fixes #1570 
- Added implementation of egg drop puzzle in C#
- This PR fixes issue #1570 
- C#
- 
- Egg_drop.cs
- 
Thanks!
=> Added Egg_Drop problem implementation in C#

Boyer_Moore_Algorithm/Boyer_Moore.java
Fixes #1666
- Boyer moore algorithmn added
- 
- Java
- 
- Boyer_Moore.java
- 
Thanks!
=> added boyer moore algo in java

Sum_Of_Digits/Sum_Of_Digits.js
Fixes #1610 
- Implemented the said problem in JS.
- JavaScript
- Sum_Of_Digits.js
Thanks!
=> Sum of digits implemented in JS. Closes #1610

Fibonacci_Number/Fibonacci_Number.php
Fixes #1631 
- The necessary script for implementation of Fibonacci Numbers in PHP.
- PHP 
- Fibonacci_Number.php
Thanks!
=> Fibonacci_Number.php added

BFS_Disconnected_Graph/BFS_DisconnectedGraph.java
Fixes #1617 
- Implementation of BFS for Disconnected Graph using Queue and Linked List
- 
- Java
- 
- BFS_DisconnectedGraph.java 
- 
Thanks!
=> BFS for Disconnected Graph in Java

Linked_List/StartOfLoop.java
Fixes #1606 
- Added a method to find starting node of a loop in a linked list
- JAVA
- StartOfLoop.java
Thanks!
=> Start of loop in a linked list

Activity_Selection/README.md
Fixes #2117
- Added Readme.md file
- Readme.md
Thanks!
=> ADDED Readme for Activity Selection

Set_Bits_Till_N/Set_Bits_Till_N.js
Fixes #1990 
- Added Implementation of Set Bits Till N in JavaScript
- JavaScript
- Set_Bits_Till_N.js
Thanks!
=> Added JS Implementation for Set_Bits_Till_N

Dijkstra_Algorithm/Dijkstra_Algorithm.js
Fixes #1881 
- The Dijkstra Algorithm is implemented using JS
- JavaScript 
- Added a file named Dijkstra_Algorithm.js inside the Dijkstra_Algorithm folder.
Thanks!
=> Implementation of Dijkstra Algorithm in JS

Cycle_Sort/Cycle_Sort.js
Fixes #1699 
- Added Cycle Sort algorithm in JS
- JavaScript
- Cycle_Sort.js
Thanks!
@raghav-dalmia
=> Cycle sort in JS. Closes #1699

Bucket_Sort/Bucket_Sort.kt
Fixes #2124 
- Bucket Sort in Kotlin
- Kotlin
- Bucket_Sort.kt
Thanks!
=> Bucket Sort in Kotlin

Depth_First_Search/Depth_First_Search.js
Fixes #1695 
- Added DFS in JS
- JavaScript
- Depth_First_Search.js
Thanks!
=> Depth first search in JS. Closes #1695

Tree_Postorder_Traversal/Tree_Postorder_Traversal.js
Fixes #1693 
- I have added Tree_Postorder_Traversal implementation in JavaScript.
- JavaScript
- Tree_Postorder_Traversal.js
Thanks!
=> Added Tree_Postorder_Traversal implementation in JavaScript.

Array_Rotation/Array_Rotation.cpp
Fixes #1726 
- created a dynamic array 
- deleting a dynamic array when its uses is finish
- c++
- 
- updated Array_Rotation.cpp
- 
Thanks!
=> updated Array_Rotation.cpp

Gcd/gcd.js
Fixes #1967
- ☑ 4 space indentation.
- ☑ Coding conventions are followed.
- ☑ Input is taken dynamically.
- ☑ Sample Input / Output is added at the end of file.
- ☑ Logic Documentation (Comments).
- ☑ File names are correct.
JS file for the problem added in gcd problem folder
JavaScript
gcd.js 
@asha15 
Thanks!
=> Solution for #1967

Rat_in_maze/Rat_in_maze.cpp
Fixes #1654 
- Rat in Maze problem by BackTracking
- 
- c++
- 
- Rat_in_maze/Rat_in_maze.cpp
- 
Thanks!
=> Rat In Maze

Machine_Learning/Linear_Regression/README.md
Fixes #1557 
- Added a simple descriptive README file to make understanding of Linear Regression easier.
- 
- English
- 
- README.md
- 
Thanks!
=> FIXES #1557 [Added README File]

1-D_Array/Java/Eveodd.java
code to find even,odd digits and their count in an array.
Fixes #1467 
- code added to find even, odd numbers and their count in an array.
- 
- Java.
- 
[Eveodd.docx](https://github.com/jainaman224/Algo_Ds_Notes/files/4282784/Eveodd.docx)
- 
Thanks!
=>  Eveodd.java #1467

Matrix_Chain_Multiplication/Matrix_Chain_Multiplication.py
Fixes #1793 
- Matrix chain multiplication added for python
- python3
- MatrixChainMultiplication.py
Thanks!
=> added matrix chain multiplication for python

Pigeonhole_Sort/Pigeonhole_Sort.cs
Update Pigeonhole_Sort.cs
Update Pigeonhole_Sort.cs
Fixes #2149 
- Added Pigeonhole sort in C#
- 
- C#
- 
- Pigeonhole_Sort.cs
- 
Thanks!
=> Added Pigeonhole_Sort.cs

Check_Palindrome_for_LinkedList/Palindrome.cpp
Fixes #2067 
- 
- 
- 
- 
- 
- 
Thanks!
=> Code to check whether a LinkedList contains Palindromic data or not

Matrix_Chain_Multiplication/Matrix_Chain_Multiplication.c
Fixes #1794 
- Matrix chain multiplication in C language added
- C
- Matrix_Chain_Multiplication.c
Thanks!
=> Matrix chain multiplication in C language.

Digit_Count/Digit_Count.rb
Fixes #1993 
- Added Digit_Count.rb
- 
- Ruby
- 
- Digit_Count.rb
- 
Thanks!
=> Added Digit_Count.rb

Armstrong_Number/Armstrong_Number.php
Fixes #2120
Since I'm using PHP It is impossible to take input from CLI. So the Input is taken statically.
- Implemented the Armstrong number code in PHP It helps us to identify whether a given number is Armstrong number or not.
- PHP
- Armstrong_Number.php
Thanks!
=> Implemented Armstrong Number in PHP. Issue Number: #2120

Quick_Sort/Quick_Sort.js
Fixes #1568 
- The previous implementation had ES5 syntax, I updated it to ES6+ and used recursive definition
- JavaScript
- Only updated the file rather than adding a new one.
Thanks!
=> QuickSort Implementation updated to ES6+ syntax in JS

Subsequence_Bitmasking/subsequence_bitmasking.cpp
Fixes #1722 
- C++
- 
- Subsequence_bitmasking 
- 
Thanks!
=> Subsequence of string using bitmasking

Regula_Falsi_Method/regula_falsi.cpp
Fixes #1916 
- Added a C++ implementation of Regula Falsi method to find roots of polynomials.
- C++
- regula_falsi.cpp
Thanks!
=> Added C++ implementation of Regula Falsi method

Karatsuba_Algo/Karatsuba_multiplication_algo.java
Fixes #1684
- Karatsuba Multiplication Algorithm
- 
- Java
- 
- Karatsuba_Algo/Karatsuba_multiplication_algo.java
- 
Thanks!
=> Karatsuba Multiplication Algorithm in java  #1684 (GSSoC'20)

Anagram/Anagram.cpp
Fixes #1569 
- One hash table used instead of two hash tables.
- 
- C++
- 
-  
- 
- 1 modified.
- Anagram.cpp file modified
Thanks!
=> Anagram Program modified .

1-D_Array/Java/Eveodd.java
Reverts jainaman224/Algo_Ds_Notes#2385
=> Revert "Revert " Eveodd.java #1467""

Longest_Common_Subsequence/Longest_Common_Subsequence.js
Fixes #2252 
- Added implementation of Longest Common Subsequence in JS
- JavaScript 
- Added file names Longeest_Common_Subsequence.js inside Longeest_Common_Subsequence folder
Thanks!
=> Completion of LCS implementation in JS issue#2252

1-D_Array/Ruby/Frequency_Of_A_Element.rb, 1-D_Array/Ruby/Max_And_Next_Max_Number.rb, 1-D_Array/Ruby/Mean_Variance_Standard_Deviation.rb, 1-D_Array/Ruby/Merge_Two_Sorted_Arrays.rb
Fixes #1826
- Finding frequency of an element in an array
- Max and next max number in array
- Mean Variance and standard deviation
- Merge two sorted arrays
-  Ruby
- 1-D_Array/Ruby/Frequency_Of_a_element.rb
- 1-D_Array/Ruby/Max_And_Next_Max_Number.rb
- 1-D_Array/Ruby/Standard_Deviation_Mean_Variance.rb
- 1-D_Array/Ruby/Merge_Two_Sorted_Array.rb
Thanks!
=> added 1-D array in Ruby

Arithmetic_Progression/Arithmetic_Progression.cs
Fixes #1637 
- Created code for Arithmetic Progression in C Sharp
- 
- C#
- 
- Arithmetic_Progression.cs
- 
Thanks!
=> Added Arithmetic Progression in C Sharp

Infix_To_Postfix/Infix_to_Postfix.py, nCr mod P/nCr_mod_P.cpp
Fixes #1772 
-  A program to convert given infix expression to postfix expression and output the evaluated result.
-  Python 3
- infix_to_postfix.py
Thanks!
=> infix-to-postfix

Quick_Hull/Quick_Hull.cpp, Quick_Hull/Quick_Hull.py
Fixes #736 
- Cpp
- Python
- Quick_Hull.py
- Quick_Hull.cpp
Thanks!
@jainaman224
=> Quick Hull implementation in cpp and python

Leap Year Code in JavaScript/script.js
=> Issue#1867 leap year

Matrix_Operations/C/sum_of_two_matrices.c
Fixes  #1773 
- Added implementation of sum of two matrices in C.
- 
- C
- 
- 
[sum_of_two_matrices.docx](https://github.com/jainaman224/Algo_Ds_Notes/files/4306862/sum_of_two_matrices.docx)
- 
Thanks!
=> Added sum of two matrices in C.

Minimum_inversions/Minimum_inversions.cpp
Fixes #1805 
- Code added for minimum inversions required in a binary array arr[] of size N so that no adjacent elements are same.
- 
- c++
- 
- Minimum_inversions.cpp
- 
Thanks!
=> Minimum inversion cpp code added

Machine_Learning/K-means/k-means_using_c.c
Fixes #1795 
- Added Kmeans algorithm using C 
- C
- 
- K-means/K-means_sing_c.c
Thanks!
=> Added Kmeans algorithm using C

Ascii_Subsequences/ASCII_Subsequences.c, Ascii_Subsequences/ASCII_Subsequences.js, Ascii_Subsequences/ASCII_Subsequences.py
Fixes #1703
- Added ASCII_Subsequences in C,Python and JavaScript
- Removed Duplicate files
- C
- Python
- JavaScript
- ASCII_Subsequences.c
- ASCII_Subsequences.py
- ASCII_Subsequences.js
@jainaman224 @raghav-dalmia @asha15 @singh-shreya6
=> Adding ASCII_Subsequence in C, Python and JavaScript (Closes issue #1703)

Power_Of_Two/Power_Of_Two.js
Fixes #1968 
- ☑ 4 space indentation.
- ☑ Coding conventions are followed.
- ☑ Input is taken dynamically.
- ☑ Sample Input / Output is added at the end of file.
- ☑ Logic Documentation (Comments).
- ☑ File names are correct.
Added solution for Power_Of_Two solution in JS file.
JavaScript
Power_Of_Two.js
Thanks!
=> added Power_Of_Two in JS

Pascal_Triangle/Pascal_Triangle.java, Pascal_Triangle/Pascal_Triangle.py
Fixes #1818  
- Added the Pascal Triangle implemented using Python and Java to the Pascal_Triangle directory.
- Java
- Python 3
- Pascal_Triangle.java
- Pascal_Triangle.py
@SakshiShreya @singh-shreya6 @asha15 @raghav-dalmia @jainaman224 please review the PR.
Thanks!
=> Implementation of Pascal Triangle in Java and Python Added (Fixes issue #1818)

Kosaraju_Algorithm/Kosaraju_Algorithm.py
Fixes #
- 
- 
- Python
- Kosaraju_Algorithm.py
Thanks!
=> Adding Python Implementation for Kosaraju Algorithm (Issue #2246)

Bucket_Sort/Bucket_Sort.js
Fixes #2124 
- Implementation of Bucket Sort in JS
- JavaScript
-  Added Bucket_Sort.js file in Bucket_Sort folder.
Thanks!
=> Implementation of Bucket Sort in JS

Machine_Learning/K_Nearest_Neighbours/K_Nearest_Neighbours.c
Fixes #1640 
- Added the KNN Algorithm implemented using C to the Machine_Learning directory.
-  C
-  K_Nearest_Neighbours/KNN_using_c.c
@MastersAbh  @SakshiShreya @singh-shreya6 @asha15 @raghav-dalmia @jainaman224 please review the PR.
Thanks!
=> Added KNN algorithm using C

Linked_List/Length_of_Linked_List.c, Linked_List/Length_of_Linked_List.java
Fixes #213 
-  Length of linked Lists in C
-  Length of linked Lists in Java
-  C
-  Java
- LengthOfLinkedList.c
- LengthOfLinkedList.java
Thanks!
=> Length of Linked List in C, Java Added

Gnome_Sort/Gnome_Sort.c, Gnome_Sort/Gnome_Sort.cpp, Gnome_Sort/Gnome_Sort.java, Gnome_Sort/Gnome_Sort.py
Fixes #1831
- Implemented the Gnome_Sort Algorithm From Scratch.
- C
- C++
- Java
- Python
-  Gnome_Sort.c
-  Gnome_Sort.cpp
- Gnome_Sort.java
- Gnome_Sort.py
Thanks!
=> Implemented the Gnome Sort Completely.

Karatsuba_Algorithm/Karatsuba_Algorithm.js
Fixes #2248 
-  Implementation of Karatsuba Algorithm in JS.
- JavaScript 
- Added a file named Karatsuba_Algorithm.js in Karatsuba_Algorithm folder.
Thanks!
=> Implementation of Karatsuba Algorithm in JS

Largest_Common_Multiple/Largest_Common_Multiple_1-DArray.c, Largest_Common_Multiple/Largest_Common_Multiple_1-DArray.cpp, Largest_Common_Multiple/Largest_Common_Multiple_1-DArray.java
Fixes # #1821
- Added code to find LCM of N array of elements
- C 
- C++
- JAVA
- LCM.c
- LCM.cpp
- LCM.java
Thanks!
=> LCM of N elements of an array Issue No. #1821

Postfix_Evaluation/Postfix _Evaluation.c
Postfix evaluation in C
Fixes ##1552
-  Implemented Postfix Evaluation in C
- 
-  C
- 
- Postfix_Evaluation.c
- 
Thanks!
=> Postfix Evaluation in C

Ternary_Search/Ternary_Search.cs
Fixes #2176 
Adding Ternary Search in C#
C#
Ternary_Search.cs
Thanks!
=> Ternary Search in C# (#2176)

Collections/arrayList.java
Fixes #1889 
- 
- 
- 
- 
- 
- 
Thanks!
=> Implementing ArrayList in Java

palindromic_string/palindromic_string.c, palindromic_string/palindromic_string.cpp
Fixes #1706
- 
- 
- C
- C++
- palindromic_string.c 
- palindromic_string.cpp 
Thanks!
=> Palindromic_string_added 2 C/C++

Palindrome/palindrome_string.java
Issue no #1718
- Added a new code
- 
- Java
- 
- palindrome_string.java
- 
Thanks!
=> check palindrome in a string in Java

Tower_Of_Hanoi/Tower_Of_Hanoi.go
Fixes #2479 
- Go Code for Tower of Hanoi added
- Go
- Tower_Of_Hanoi.go
Thanks!
=> Added code for Tower Of Hanoi in Go language

Merge_Sort_3_Way/Merge_Sort_3_Way.cpp
Fixes #521
- 3 Way Merge Sort code implementation.
- C++ 
- Merge_Sort_3_Way.cpp
Thanks!
=> Merge-sort-3-way-in-cpp

Count_Rotations/Count_Rotations.java
Fixes #1634 
- Added method to find how many times a sorted array is rotated using Binary Search
- JAVA
- RotationCount.java
Thanks!
=> Rotations in sorted array

Integer_to_Roman/Integer_to_Roman.cpp
Fixes #2216 
- Added Integer to Roman Program in C++
- C++
- Integer_to_Roman.cpp
Thanks!
=> Integer to Roman in C++

Postman_Sort/Postman_Sort.cs
Fixes # #2251
- Created a Folder Postman_Sort
- Added a file Postman_Sort.cs
- C#
- Postman_Sort.cs
Thanks!
=> Postman Sort in C#

Circle_Sort/Circle_Sort.kts
Fixes #2129
- Added Circle Sort Algo in Kotlin
- 
-  Kotlin
- 
-  Circle_Sort.kts
- 
Thanks!
=> CircleSort Algo in Kotlin

Armstrong_Number/Armstrong_Number.cs
Fixes #1954 
- Added program to check whether a number is armstrong or not in C#
- C#
- armstrong.cs
Thanks!
=> Add Armstrong Number In C# Fixes #1954

Tower_Of_Hanoi/Tower_Of_Hanoi.kt
Fixes #2479
- Kotlin Code for Tower of Hanoi added
- Kotlin
- Tower_Of_Hanoi.kt
Thanks!
=> Tower of Hanoi in Kotlin

Tower_Of_Hanoi/Tower_Of_Hanoi.php
Fixes #2479 
- Added PHP implementation of Tower Of Hanoi
- 
- PHP
- 
- Tower_Of_Hanoi/Tower_Of_Hanoi.php
- 
Thanks!
=> Added Tower Of Hanoi in PHP

Tower_Of_Hanoi/Tower_of_Hanoi.dart
Fixes #2479 
- Added multi-line comments to describe the problem
- Added new line at the end of file
- 4-space indentation applied
- Dart
- 
- Tower_of_Hanoi.dart
- 
Thanks!
=> Tower of Hanoi in Dart

Jhonson_Algoritm/Jhonson.cs
Fixes #2206
- Added file for Jhonson Algorithm
- 
- C#
- Jhonson.cs
Thanks!
=> Jhonson Algorithm in C#

Topological_Sort/Topological_Sort.js
Fixes #2159 
- Added Topological_Sort.js
- JavaScript
- Topological_Sort.js 
Thanks!
=> Added Topological_Sort.js (Fixes #2159)

Matrix_Operations/Java/Matrix_Addition.java
Issue No #1628
- 
- Java
- 
- Matrix_Addition.java
- 
Thanks!
=> Addition of matrix in java

Priority_Queue/Priority_Queue.py
Here is my new PR for priority queue in python, an alternative PR for already existing PR #2280.
fixes issue #970
Fixes #
- 
- 
- 
- 
- 
- 
Thanks!
=> Priority_Queue.py

Z_Algorithm/Z_Algorithm.js
Fixes #2478 
- Implementation of Z-Algorithm in Javascript
- JavaScript
- Added a file names Z_Algorithm.js in Z_Algorithm folder
Thanks!
=> Added implementation of Z-Algorithm in JS

Pancake_Sort/Pancake_Sort.cs
@jainaman224 
Fixes #2151 
- Added Pancake Sort Algorithm in C#
- C#
- Pancake_Sort.cs
Thanks!
=> Created Pancake Sort in C#

Johnson_Algorithm/Johnson_Algorithm.dart
Fixes #2206 
-Added Johnson Algorithm implementation in dart 
- Dart
- Johnson_Algorithm.dart
@jainaman224 @SakshiShreya @raghav-dalmia
=> Johnson Algorithm Implementation in Dart

Boyer_Moore_Algorithm/Boyer_Moore.cs
Fixes #2480 
- Boyer Moore Algorithm in C#
- 
- C#
- 
- Boyer_Moore.cs
- 
Thanks!
=> Boyer Moore Algorithm in C#

Chinese_Remainder_Theorem/Chinese_Remainder_Theorem.php
Fixes #2481 
- 
- 
- PHP
- Chinese_Remainder_Theorem.php
Thanks!
=> Adding PHP Implementation for Chinese Remainder Theorem (Issue #2481) 

Tree_Inorder_Traversal/Tree_Inorder_Traversal.js
Fixes #2552
- Added Tree_Inorder_Traversal.js
- JS
- Added Tree_Inorder_Traversal.js 
Thanks!
=> Added Tree Inorder Traversal in JS

Floyd_Warshall_Algorithm/Floyd_Warshall.js
Fixes https://github.com/jainaman224/Algo_Ds_Notes/issues/2205
- Floyd warshall in javascript
- java script
- Floyd_Warshall.js
Thanks!
=> Floyd warshal js

Number_Conversion/Java/Decimal_to_binary.java
Fixes #964
- added Decimal_to_binary conversion
- 
- java
- 
- Decimal_to_binary.java
- 
Thanks!
=> Added a Number conversion(Decimal to Binary) code in java

Chinese_Remainder_Theorem/Chinese_Remainder_Theorem.go
Fixes #2481 
- Chinese Remainder Theorem in Go
- 
- Go
- 
- Chinese_Remainder_Theorem.go
- 
Thanks!
=> Chinese Remainder Theorem in Go

Quicksort_3_way/quick_sort_3_way.rb
Fixes #2170
-  Implemented QuickSort in Ruby
- 
-  Ruby
- 
-  quick_sort_3_way.rb
- 
Thanks!
=> Quick Sort 3 way in Ruby

Dijkstra_Algorithm/Dijkstra_Algorithm.dart
Fixes #2204 
- Added Implementation of Dijkstra Algorithm in dart 
- Dart
- Dijkstra_Algorithm.dart
@jainaman224 @raghav-dalmia @singh-shreya6 @asha15
=> Dijkstra Algorithm implementation in dart

Selection_Sort/Selection_Sort.ts
Fixes #2154 
- Selection sort logic in Typescript
- Typescript
- Selection_Sort.ts
Thanks!
=> added selection sort logic in typescript

Tower_Of_Hanoi/Tower_Of_Hanoi.rb
Fixes #2479 
- Tower Of Hanoi in Ruby
- 
- Ruby
- 
- Tower_Of_Hanoi.rb
- 
Thanks!
=> Tower Of Hanoi In Ruby

Boyer_Moore_Algorithm/Boyer_Moore.c
Fixes #2480 
- Boyer Moore Algorithm code added in C language.
- 
- C
- 
- Boyer_Moore.c
- 
Thanks!
=> Boyer Moore Algo in c 

Boyer_Moore_Algorithm/Boyer_Moore.go
Fixes #2480
- Boyer Moore Implementation in Go
- 
- Go
- 
- Boyer_Moore.go
- 
Thanks!
=> Boyer Moore in Go

Kruskal_Algorithm/Kruskal_Algorithm.c
Fixes #1991 
- Kruskal Algorithm in C
- C
- Kruskal_Algorithm.c
Thanks!
=> Kruskal Algorithm in C

Breadth_First_Search/Breadth_First_Search.rb
Fixes #2171 
- Breadth First Search in Ruby
- Graph is taken using Adjacency Matrix
- Traversal starts from Source
- Ruby
- 
- Breadth_First_Search.rb
- 
Thanks!
=> Breadth First Search in Ruby

Backtracking_using_bitmask/Backtrack_using_bitmask.cpp, Backtracking_using_bitmask/Backtrack_using_bitmask.java, Backtracking_using_bitmask/Backtrack_using_bitmask.py
Fixes 
#1597
Backtracking Using Bitmasking
Backtracking is an algorithmic-technique for solving problems recursively by trying to build a solution incrementally, one piece at a time, removing those solutions that fail to satisfy the constraints of the problem at any point of time.
Here, we'll be taking the case of a backtracking based problem: N Queen problem.
The N Queen is the problem of placing N chess queens on an N×N chessboard so that no two queens attack each other.
We'll be implementing the solution using backtracking and bit masking in various programming languages.
- CPP
- JAVA
- Python
- Backtrack_using_bitmask.cpp
- Backtrack_using_bitmask.java
- …
=> Backtracking

Matrix_Operations/Java/Matrix_transpose.java
issue no #1628 
- 
- Java
- 
- Matrix_transpose.java
- 
Thanks!
=> Transpose of matrix in java

Kruskal_Algorithm/Kruskal_Algorithm.py
Used disjoint set data structure for Algorithm implementation.
Fixes #2200  
- Added implementation of Kruskal Algorithm
- 
- Python 3.6
- 
- Kruskal_Algorithm.py
- 
Thanks!
=> Kruskal Algorithm Implementation in python

Tree_Preorder_Traversal/Tree_Preorder_Traversal.dart
Fixes #2550
- Tree preorder traversal implemented in Dart
- Dart
- Tree_Preorder_Traversal.dart
Thanks!
=> Tree Preorder Traversal in Dart

Shell_Sort/Shell_Sort.go
Fixes #2156 
- Shell sort algorithm in Go
- Go
- Shell_Sort.go
Thanks!
=> added shell sort algorithm in go

Median_Sorted_Arrays/Median_Sorted_Arrays.cpp
Fixes #2018 
Description - The previous PR had issues due to squashing of commits.
- Median of Two Sorted Arrays 
- New PR , Old closed
- C++
-
=> :star: add median of two sorted arrays

Segment_Tree_RMQ/Segement_Tree_RMQ.c
Fixes #2164
- 
- 
- 
- 
- 
- 
Thanks!
=> Segment Tree Range Minimum Query in  C

Depth_First_Search/Depth_First_Search.cs
Fixes #2172 
Code added for Depth First Search in C#
- C#
- Depth_First_Search.cs
Thanks!
=> Depth First Search in C#

Longest_Increasing_Subsequence/LIS.java
Fixes #2253 
- Java Code for Longest Increasing Subsequence added
- Java
- LIS.java
Thanks!
=> Added code of Longest Increasing Subsequence in Java

AVL_Tree/AVL_Tree.cpp
Fixes #2112 
- Adding implementation of AVL Tree
- 
- C++
- 
- 
- 
Thanks!
=> AVL Tree implementation in C++

Prims_Algorithm/Prims_Algorithm.cs
Fixes #2201
- Prims Algorithm 
- 
- C#
- 
- Primis_Algorithm.css
- 
Thanks!
=> Prims Algorithm in C#

Jhonson_Algoritm/Jhonson_Algorithm.php
Fixes #2206
- Implemented Jhonson Algorithm in PHP
- PHP
- Jhonson_Algorith.php
Thanks!
=> Jhonson Algorithm in PHP

Fenwick_Tree/Fenwick_Tree.php
Fixes #2173 
- Fenwick_Tree.php Added
- PHP
- Fenwick_Tree.php
Thanks!
=> Fenwick_Tree.php Added

Breadth_First_Search/BFS_in_Csharp.cs
Fixes #2171 
- Breadth-First Search Code implemented using queue in C# added
-  C#
- bfs_in_Csharp.cs file added
Thanks!
=> Breadth First Search in Csharp  #2171

Chinese_Remainder_Theorem/Chinese_Remainder_Theorem.dart
Fixes #2481 
- Chinese Remainder Theorem is implemented in Dart
- Dart
- Chinese_Remainder_Theorem.dart
Thanks!
=> Chinese remainder theorem dart

Johnson_Algorithm/Johnson_Algorithm.c
Fixes #2206
- Addition of folder for Johnson Algorithm
- Addition of code for Johnson Algorithm in C
- C
- Johnson_Algorithm.c
Thanks!
=> Johnson Algorithm implementation in C (Issue #2206)

Spiral_Array/SpiralArray.c
<Issue number #960  >
Fixes #
- Added code for spiral array with test inputs.
- Added spaces around operator.
- C
- 
- spiralarray.c
- 
Thanks!
=> Add spiral array in C

Merge_Sort/Merge_Sort.rs
Fixes #2136 
- Merge Sort in Rust 
- Rust
- Merge_Sort.rs
Thanks!
=> Merge Sort in Rust

Heap_Sort/heap_sort.php
Fixes #2147
- added a new file
- PHP
- heap_sort.php
Thanks!
=> added PHP/Heap sort (#2147)

Bucket_Sort/Bucket_Sort.rb
Fixes #2124 
- Bucket Sort in Ruby
- Ruby
- Bucket_Sort.rb
Thanks!
=> Bucket Sort in Ruby

Topological_Sort/Topological_Sort.dart
Fixes #2159 
- Topological Sort implemented in Dart
- Implemented using adjacency list
- Dart
- Topological_Sort.dart
Thanks!
=> Topological Sort implemented in Dart

Tower_Of_Hanoi/Tower_of_Hanoi.cs
=> Implementation Of Tower of Hanoi in C#

Insertion_Sort/README.md
Fixes #2148
- Written documentation for Insertion Sort Algorithm
- Markdown (md)
- README.md
Thanks!
=> Insertion Sort #2148

Segment_Tree_RMQ/Segment_Tree_RMQ.dart
Fixes #2164 
- Segment Tree is implemented in Dart for Range Minimum Queries
- Dart
- Segment_Tree_RMQ.dart
Thanks!
=> Segment Tree RMQ implemented in Dart

Chinese_Remainder_Theorem/Chinese_remainder_theorem.c
Fixes  #2481
- Added implementation of Chinese remainder theorem in C.
- C
- 
[chinese_remainder_theorem.docx](https://github.com/jainaman224/Algo_Ds_Notes/files/4551712/chinese_remainder_theorem.docx)
- 
Thanks!
=> Added Chinese remainder theorem in C.

Gray_Code/Gray_Code.cpp
Fixes #1644 
- Added the code which prints the Gray Code sequence of any input length given as input by user.
- 
- C++
- 
- [Gray Code.cpp](https://github.com/SubhradeepSS/Algo_Ds_Notes/blob/Gray-Code/Gray%20Code.cpp)
- 
Thanks!
=> Gray Code of input length

Postman_Sort/readme.md
Fixes #2251 
- Readme added
- 
- 
- 
- readme.md
- 
Thanks!
=> Postman sort readme added

RSA_CRT/RSA_CRT.cpp
Fixes #2021
-  Implementation of RSA algorithm using Chinese remainder theorem in C++  
- C++
- RSA_CRT.cpp
Thanks!
=> 'c++_implementation_of_RSA_CRT'

Rabin_Karp/Rabin_Karp.py
Fixes #2019 
- Python Implementation of Rabin Karp Algorithm
- Python
-    ###Rabin_Karp.py
Thanks!
=> 'Python_Implementation_of_Rabin_Karp'

Dijkstra_Algorithm/Dijkstra_Algorithm.ts
Fixes #2204 
-  added Dijkstra algorithm in Typescript
-  Typescript
-  Dijkstra_Algorithm.ts
Thanks!
=> added typeScript implementation of Dijkstra Algorithm

Floyd_Warshall_Algorithm/Floyd_Warshall_Algorithm.rb
Fixes #2205 
- Floyd Warshall Algorithm in Ruby
- 
- Ruby
- 
- Floyd_Warshall_Algorithm.rb
- 
Thanks!
=> Floyd Warshall Algorithm In Ruby

Binary_Search_Trees/BinarySearchTree.dart
New PR with squashed commits with reference to PR #2429 
Fixes #
- Indentation changed
- Squash commit
- Dart
Thanks!
=> Binary Search Tree in dart language

Linear_Search/Linear_Search.dart
Linear search algorithm in dart
Fixes #2179 
- Dart
Thanks!
=> Linear Search in dart language

Depth_First_Search/Depth_First_Search.go
Fixes #2172 
- Added Depth First Search in Go
- Go
- Depth_First_Search.go
Thanks!
=> Depth First Search in Go

Quick_Sort/Quick_Sort.kt
Fixes #2131 
- implementation of quicksort algorithm in kotlin.
- Kotlin
- Quick_Sort.kt
Thanks!
=> Quick Sort Implementation in Kotlin

Matrix_Operations/Java/Matrix_identical.java
issue no #1628 
- 
- Java
- 
- Matrix_identical.java
- 
Thanks!
=> Matrix_identical in java

Binary_Search/Binary_Search.dart
=> Binary search in dart language

Knuth_Morris_Pratt_Algorithm/KMP.js
Fixes #2555 
- Added KMP algorithm written in JavaScript.
- JavaScript
-  KMP.js
Thanks!
=> KMP in JavaScript was added

Longest_Common_Subsequence/Longest_Common_Subsequence.php
Fixes #2252
- Added the LCS in PHP
- 
- PHP
- 
- Longest_Common_Subsequence.php
- 
Thanks!
=> #2252 - Added LCS in php

Matrix_Operations/Java/Matrix_multiply.java
Fixes #1628 
- 
- Java
- 
- Matrix_mutiply.java
- 
Thanks!
=> Multiplication of 2 matrices in java

Shell_Sort/Shell_Sort.php
Fixes #2156 
- Added Shell Sort in PHP
- PHP
- Shell_Sort.php
Thanks!
=> Created Shell_Sort.php

Prims_Algorithm/Prims_Algorithm.js
Fixes #2201 
- 
- 
- JS
- Prims_Algorithm.js
Thanks!
=> Adding Prim's algorithm in JS (Issue #2201)

Fenwick_Tree/Fenwick_Tree.c
#2173 Added C implementation of Fenwick Tree Algorithm(Issue #2173 )
Fixes #2173 
- added C file for fenwick tree algorithm
- C
- fenwick_tree.c
Thanks!
=> adding c file of fenwick tree

Matrix_Operations/Java/Matrix_Subtraction.java
Issue no #1628 
- 
- Java
- 
- Matrix_Subtraction.java
- 
Thanks!
=> Subtraction of matrix in java

Knuth_Morris_Pratt_Algorithm/KMP.dart
Fixes #2555 
-  Brief Description added
-  Added Line between Functions
-  Added line at the end of file
-  Dart
-  KMP.Dart
Thanks!
=> KMP algorithm in dart added

Selection_Sort/Selection_Sort.php
Fixes #2154 
- PHP
- Selection_Sort.php
=> Added Selection_Sort.php

Matrix_Operations/Java/Matrix_intersection.java
Fixes #1628 
- 
- Java
- 
- Matrix_intersection.java
- 
Thanks!
=> Matrix_intersection in java

Chinese_Remainder_Theorem/Readme.md
Fixes #2481 
- Chinese_Remainder_Theorem/Readme.md
- 
- 
- 
- Chinese_Remainder_Theorem/Readme.md
- 
Thanks!
=> Readme.md for Chinese_Remainder_Theorem

Segment_Tree_RMQ/README.md
Fixes #2164 
- Added Readme.md for Segment_Tree_RMQ
- 
- 
- 
- Segment_Tree_RMQ/Readme.md
- 
Thanks!
=> Readme for Segment_Tree_RMQ

Number_Conversion/Java/Binary_To_Octal.java
Fixes #865 
- Added a file binary to octal.java
- 
- Java
- 
- Binary_to_octal.java
- 
Thanks!
=> Number Convertions Binary to Octal in Java#865

Kosaraju_Algorithm/Kosaraju_Algorithm.cs
Fixes #2246
- 
- 
- C#
- Kosaraju_Algorithm.css
Thanks!
=> Kosraju Algorithm in C#

Z_Algorithm/Z_Algorithm.rs
Fixes #2478
- Z Algorithm implementation in Rust
- 
- Rust
- 
- Z_Algorithm.rs
- 
Thanks!
=> Z Algorithm in Rust

Boyer_Moore_Algorithm/Readme.md
Fixes #2480 
- Added the Readme file of Boyer Moore Algorithm
- Markdown
- Create Readme.md(#2480 )
Thanks!
=> Create Readme.md ( Boyer_Moore_Algorithm)

Heap_Sort/heapsort.go
Fixes #2147
-  Implemented heap sort by creating Max heap
-  Corrected Indentation
-  Go
- 
-  heapsort.go
- 
Thanks!
=> Go Implementation of Heapsort

Knuth_Morris_Pratt_Algorithm/KMP.kt
Fixes #2555 
- Added Knuth Morris Pratt Algorithm in Kotlin
- Kotlin
- KMP.kt
Thanks!
=> Added Knuth Morris Pratt Algorithm in Kotlin

Knuth_Morris_Pratt_Algorithm/KMP.rb
Fixes #2555 
- Added implementation of KMP algorithm in Ruby
- Ruby
- Added KMP.rb under Knuth_Morris_Pratt_Algorithm folder
Thanks!
=> Added KMP implementation in Ruby (#2555)

Depth_First_Search/Depth_First_Search.php
Fixes #2172 
- Added DFS in PHP
- 
- PHP
- 
- Depth_First_Search.php
- 
Thanks!
=> Added DFS in PHP

Intro_Sort/introsort.py
Fixes #2249
-New folder Intro_sort is created
- Python code for introsort is added in introsort.py
-Python
- 
-  A python file introsort.py in Intro_Sort
=> Intro Sort implementation in Python

Rabin_Karp/Rabin_Karp.c
Fixes #2161 
- Brief description added
- Variables added
- C
- Rabin_Karp.c
Thanks!
=> Rabin Karp in C

Sleep_Sort/README.md
Fixes #2157 
- 
- 
- 
- 
- README.md
- 
Thanks!
=> sleep sort README.md file 

Bucket_Sort/Bucket_Sort.go
Fixes #2124 
- Bucket Sort in go
- Go
- Bucket_Sort.go
Thanks!
=> Bucket Sort in Go

Red_Black_Tree/Red_Black_Tree.cs
Fixes #2163
- Red Black Tree implementation in C#
- C#
- Red_Black_Tree.cs
Thanks!
=> Red Black Tree implementation in C#

AVL_Tree/AVL_Tree.dart
Fixes #2112 
- AVL Tree is implemented in Dart.
- Insertion and deletion operations are implemented.
- Dart
- AVL_Tree.dart
Thanks!
=> AVL Tree implemented in Dart

Jhonson_Algoritm/Jhonson_Algorithm.kt
Fixes #2206
- Jhonson Algorithm in Kotli
- 
- 
- Jhonson_Algorithm.kt
Thanks!
=> Jhonson Algorithm in Kotlin

Z_Algorithm/Z_Algorithm.cs
Fixes #2478 
- Z Algorithm In C#
- 
- C# 
- 
- Z_Algorithm.cs
- 
Thanks!
=> Z Algorithm In C#

Circle_Sort/Circle_Sort.rb
Fixes #2129 
- Circle Sort In Ruby
- 
- Ruby
- 
- Circle_Sort.rb
- 
Thanks!
=> Circle Sort In Ruby

Postman_Sort/Postman_Sort.cpp
Fixes #2251 
- Added Postman Sort in C++
- C++
- Postman_Sort.cpp
Thanks!
=> Postman Sort in C++

Bubble_Sort/Bubble_Sort.rs
Fixes #2143  
- Bubble Sort in Rust 
- Rust 
- Bubble_Sort.rs 
Thanks!
=> Bubble Sort in Rust

Merge_Sort/Merge_Sort.ts
Fixes #2136 
- Added Merge Sort in Typescript 
- Typescript
- Merge_Sort.ts
Thanks!
=> Merge_Sort in Typescript

Counting_Sort/Counting_Sort.kt
Fixes #2145 
- Add Counting Sort in Kotlin
- Kotlin
- Counting Sort in Kotlin
Thanks!
=> Add Counting Sort in Kotlin

Selection_Sort/Selection_sort.rs
Fixes #2154
- added new code
- 
- Rust
- 
- Selection_sort_rust.rs
- 
Thanks!
=> Selection sort in rust

Bubble_Sort/Bubble_Sort.cpp
- Fixed a typing mistake
- 
- C++
- 
- 
- 
Thanks!
=> Fixed a typo in the Bubble_Sort.cpp

Floyd_Cycle_Detection_Algorithm/README.md
Fixes #1885 
- 
- I have added README file for Flyod Cycle Detection Algorithm
- 
- markdown
- 
- README.md
Thanks!
=> Added Readme

Dijkstra_Algorithm/Dijkstra_Algorithm.php
Fixes #2204 
- 
- 
- PHP 
- Dijkstra_Algorithm.php
Thanks!
=> Adding PHP Implementation of Dijkstra's Algo. (Issue #2204)

Ford_Fulkerson_Method/Ford_Fulkerson_Method.js
Fixes #2477
- Added Javascript code for Ford Fulkerson Method
- Javascript
- Ford_Fulkerson_Method.js
Thanks!
=> Added Ford Fulkerson Method in Javascript

Linear_Search/Linear_Search.rs
linear search in rust
Fixes #2179 
- Added new file
- 
- Rust
- 
- Linear_Search.rs
- 
Thanks!
=> linear search in rust

Extended_Euclidean_Algorithm/Extended_Euclidean_Algorithm.java
Fixes #2906 
- Implemented the extended euclidean algorithm in Java
- Java
- Extended_Euclidean_Algorithm.java
=> Added extended euclidean algorithm in java

Exponential_Search/Exponential_Search.php
Fixes #2177
- Added Exponential Search in PHP
- 
- PHP
- 
- Exponential_Search.php
- 
Thanks!
=> Added Exponential Search in PHP

Aho-Corasick/Aho-Corasick.py
Fixes #2118
- Add Code in Python 3
- 
- Python
- 
- Aho-Corasick.py
- 
Thanks!
=> Add Aho-Corasick in Python

Binary_Search/Binary_Search.rs
Fixes #2175 
- added new code
- 
- Rust
- 
- Binary_search.rs
- 
Thanks!
=> Binary search in rust

Shell_Sort/Shell_Sort.rb
Fixes #2156 
- Shell Sort In Ruby
- 
- Ruby
- 
- Shell_Sort.rb
- 
Thanks!
=> Shell Sort In Ruby

Tower_Of_Hanoi/Tower_Of_Hanoi.ts
Fixes #2479 
- Created Tower_Of_Hanoi program in TypeScript
- TypeScript
- Tower_Of_Hanoi.ts
Thanks!
=> Tower_Of_Honoi.ts

Extended_Euclidean_Algorithm/Extended_Euclidean_Algorithm.js
Fixes #2906 
- Extended Euclidean algorithm js file added
- 
- Javascript
- 
- Extended_Euclidean_Algorithm,js
- 
Thanks!
=> Extended euclidean

Cycle_Sort/Cycle_Sort.rb
Fixes #2146 
- Cycle Sort In Ruby
- 
- Ruby
- 
- Cycle_Sort.rb
- 
Thanks!
=> Cycle Sort In Ruby

Extended_Euclidean_Algorithm/Extended_Euclidean_Algorithm.ts
Fixes #2906
- Add code for Extended_Euclidean_Algorithm in TypeScript
- 
- TypeScript
- 
- Extended_Euclidean_Algorithm.ts
- 
Thanks!
=> Add Extended Euclidean Algorithm in TypeScript

Euclidean_Algorithm/Euclidean_Algorithm.js
Fixes #2905 
- Euclidean_Algorithm.js added
- 
- JavaScript
- 
- Euclidean_Algorithm.js
- 
Thanks!
=> Euclidean Algo added

Binary_Search/Binary search.ts
Fixes #2175 
-  TypeScript implementation of Binary Search algorithm
- 
-  TypeScript
- 
-  binary_search.ts
- 
Thanks!
=> Binary Search in TypeScript

Circle_Sort/Circle_Sort.php
Fixes #2129 
- Added circle_sort.php
- PHP
- circle_sort.php
Thanks!
=> Added circle_sort.php

Boyer_Moore_Algorithm/Boyer_Moore.php
Fixes #2480 
- 
- 
-  PHP
- Boyer_Moore.php
Thanks!
=> Adding PHP Implementation for Boyer Moore Algo. (Issue #2480)

Sieve_Of_Eratosthenes/Sieve_Of_Eratosthenes.php
Fixes #2174 
- Added sieve in PHP
- PHP
- Sieve _Of _Eratosthenes .php
Thanks!
=> Sieve Of Eratosthenes #2174

Depth_First_Search/Depth_First_Search.kt
Fixes #2172 
- Added Depth First Search in Kotlin
- Kotlin
- Depth_First_Search.kt 
Thanks!
=> Depth first search in Kotlin

Kosaraju_Algorithm/Kosaraju_Algorithm.kt
Fixes #2246
- Kosaraju Algorithm Implemenation in Kotlin
- Kotlin
- Kosaraju_Algorithm.kt
Thanks!
=> Kosaraju Algorithm Implemenation in Kotlin

Comb_Sort/Comb_Sort.kt
Fixes #2135 
- Add Comb Sort In Kotlin
- Kotlin
- Comb_Sort.kt
Thanks!
=> Comb Sort in Kotlin

Cycle_Sort/Cycle_Sort.go
Fixes #2146 
- Added Cycle Sort in Go
- Go
- Cycle_Sort.go
Thanks!
=> Cycle Sort in Go 

Pigeonhole_Sort/Pigeonhole_Sort.go
Fixes #2149 
- Added Pigeonhole Sort in Go
- Go
- Pigeonhole_Sort.go
Thanks!
=> Pigeonhole sort in Go

Dijkstra_Algorithm/readme.md
Fixes #2204
- Dijsktra algorithm readme added
- 
- 
- 
- readme.md
- 
Thanks!
=> dijkstra algo readme added

Rabin_Karp/Rabin_Karp.rb
Fixes #2161 
- Added implementation of Rabin Karp algorithm in Ruby
- Ruby
- Added Rabin_Karp.rb under Rabin_Karp folder
Thanks!
=> Added Rabin-Karp implementation in Ruby (#2161)

Euclidean_Algorithm/Euclidean_Algorithm.rb
Fixes #2905 
- Added implementation of Euclidean algorithm in Ruby
- Ruby
- Added Euclidean_Algorithm.rb under Euclidean_Algorithm folder
Thanks!
=> Added Euclidean Algorithm implementation in Ruby (#2905)

Pigeonhole_Sort/Pigeonhole_Sort.kt
Fixes #2149 
- implementing pigeonhole sort using Kotlin 
- Kotlin 
- Pigeonhole_Sort.kt
- 
Thanks!
=> Pigeonhole Sort using Kotlin

Fenwick_Tree/Fenwick_Tree.kt
Fixes #2173 
- Fenwick Tree implementation in Kotlin
- Kotlin
- Fenwick_Tree.kt
=> Added Fenwick_Tree in Kotlin

Radix_Sort/Radix_Sort.rs
Fixes #2152 
- Added Radix Sort in Rust
- Rust 
- Radix_Sort.rs 
Thanks!
=> Radix sort in Rust

Fenwick_Tree/Fenwick_Tree.cs
Fixes #2173
- Fenwick Tree implementation in C#
- C#
- Fenwick_Tree.cs
Thanks!
=> Fenwick Tree implementation in C#

Euclidean_Algorithm/Euclidean_Algorithm.ts
Fixes #2905
- Add code for Euclidean Algorithm in TypeScript
- TypeScript
- Euclidean_Algorithm.ts
Thanks!
=> Add Euclidean Algorithm in TypeScript

Radix_Sort/RadixSort.php
Fixes #2152
Checklist:
Changes proposed in this pull request:
- Radix Sort in PHP. 
Languages Used:
- PHP  
Files Added:
- RadixSort.php 
Thanks!
=> Radix Sort in PHP

Kosaraju_Algorithm/kosaraju_algorithm.js
Fixes #2246 
- Kosaraju Algorithm in JS
- JS
- kosaraju_algorithm.js
=> kosaraju algorithm in JS

Knuth_Morris_Pratt_Algorithm/KMP.php
Fixes #2124 
- Implemented the Bucket Sort in PHP
- PHP
- Bucket_Sort.php
Thanks!
=> Implemented the Bucket Sort in PHP.

Insertion_Sort/Insertion_Sort.rs
Fixes #2148 
- Added Insertion Sort in Rust
- Rust
- Insertion_Sort.rs
Thanks!
=> Insertion sort in Rust

Kruskal_Algorithm/Kruskal_Algorithm.js
Fixes #2200 
Code for Kruskal's Algorithm in Javascript
JavaScript
Kruskal_Algorithm.js
Thanks!
=> Implementation of Kruskal Algorithm in JavaScript

Prims_Algorithm/Prims_Algorithm.dart
Fixes #2201 
- Added Prims Algorithm implementation in Dart
- Dart
- Prims_Algorithm.dart
@jainaman224 @asha15 @raghav-dalmia @SakshiShreya
=> Prims Algorithm implementation in Dart

Kruskal_Algorithm/Kruskal_Algorithm.dart
Fixes #2200 
- Added Kruskal Algorithm implementation in Dart
- Dart
- Kruskal_Algorithm.dart
@jainaman224  @asha15 @raghav-dalmia @SakshiShreya @shreyakapoor08
=> Kruskal Algorithm implementation in Dart

Ternary_Search/Ternary_Search.php
Fixes #2176 
- PHP
- Ternary_Search.php 
Thanks!
=> Added Ternary_Search.php

Quicksort_3_way/Quicksort_3_way.dart
Fixes #2170 
- 3 way Quick sort is implemented in Dart
- Dart
- Quicksort_3_way.dart
Thanks!
=> 3 way quick sort implemented in Dart - #2170 resolved

Linear_Search/Linear_Search.ts
Fixes #2179
- 
- 
- typescript
- 
- Linear_Search.ts
- 
Thanks!
=> Linear search #2179

Knapsack/01_knapsack.cpp
Fixes #1992 
- Adding implementation of 0/1 knapsack using recursion in C++
- C++
- 01_knapsack.cpp
Thanks!
=> Implementation of 0/1 knapsack problem in c++

Fenwick_Tree/Fenwick_Tree.dart
Fixes #2173 
- Fenwick tree is implemented in Dart
- Dart
- Fenwick_Tree.dart
Thanks!
=> Fenwick tree implemented in Dart - #2173 resolved

Rabin_Karp/Rabin_Karp.php
Fixes #2161
- Rabin Karp Algorithm in PHP
- PHP
- Rabin_Karp.php
Thanks!
=> Rabin Karp in PHP

Rabin_Karp/Rabin_karp.js
Fixes #2161 
- Added Rabin_karp.js
- JavaScript
- Rabin_karp.js
Thanks!
=> Create Rabin_karp.js (Fixes #2161 )

Rabin_Karp/Rabin_Karp.dart
Fixes #2161 
- Rabin Karp algorithm is implemented in Dart
- Dart
- Rabin_Karp.dart
Thanks!
=> Rabin Karp implemented in Dart - #2161 resolved

Cycle_Sort/Cycle_Sort.dart
Fixes #2146 
- Cycle sort is implemented in Dart
- Dart
- Cycle_Sort.dart
Thanks!
=> Cycle sort implemented in Dart - #2146 resolved

Cocktail_Sort/Cocktail_Sort.rb
Fixes #2144 
- Cocktail Sort In Ruby
- 
- Ruby
- 
- Cocktail_Sort.rb
- 
Thanks!
=> Cocktail Sort In Ruby

Sleep_Sort/Sleep_Sort.go
Fixes #2157
- Added Sleep Sort in Go
- Go
- Sleep_Sort.go
Thanks!
=> Sleep Sort in Go

Counting_Sort/Counting_Sort.go
Fixes #2145 
- Added Counting Sort in Go
- Go
- Counting_Sort.go
Thanks!
=> Counting Sort in GO

Selection_Sort/Selection_Sort.dart
Fixes #2154 
- Selection Sort in Dart
- Dart
- Selection_Sort.dart
Thanks!
=> Selection_Sort in dart issue #2154

Sieve_Of_Eratosthenes/Sieve_Of_Eratosthenes.ts
Fixes #2174
- Add code for Sieve Of Eratosthenes in TypeScript
- TypeScript
- Sieve_Of_Eratosthenes.ts
Thanks!
=> Add Sieve Of Eratosthenes in TypeScript

Radix_Sort/Radix_Sort.dart
Fixes #2152 
- Radix sort is implemented in Dart
- Dart
- Radix_Sort.dart
Thanks!
=> Radix sort implemented in Dart - #2152 resolved

Bellmanford_Algorithm/Bellmanford.dart
Fixes #2202 
- Bellman Ford algorithm is implemented in Dart
- Dart
- Bellmanford.dart
Thanks!
=> Bellman Ford algorithm implemented in Dart - #2202 resolved

Kosaraju_Algorithm/Kosaraju_algorithm.dart
Fixes #2246 
- Kosaraju algorithm is implemented in Dart
- Dart
- Kosaraju_algorithm.dart
Thanks!
=> Kosaraju Algorithm implemented in Dart - #2246 resolved

Intro_Sort/README.md
Fixes #2249 
- Readme added
- 
- 
- 
- README.md
- 
Thanks!
=> Readme for introsort

Binary_Insertion_Sort/Binary_Insertion_Sort.dart.txt
Fixes #2125
- 
- 
- DART
- 
- Binary_Insertion_Sort.dart
- 
Thanks!
=> Binary Insertion sort in dart

Pancake_Sort/Pancake_Sort.kt, Pancake_Sort/Pancake_Sort.txt
Fixes #2151 
- Add Pancake Sort in Kotlin
- Kotlin
- Pancake_Sort.kt
Thanks!
=> Add Pancake Sort in Kotlin

Depth_First_Search/Depth_First_Search.kt, Preemptive.cpp
Fixes #1947
- 
- 
- C++
- 
- Preemptive.cpp
- 
Thanks!
@asha15
=> Preemptive priority in C++

RSA_Algorithm/README.md
Fixes #2162 
- Added README.md 
- Mardown
- README.md
Thanks!
=> README.md for RSA Algorithm

Python implementation for the Rabin Karp algorithm
Fixes #2905
- 
- 
- 
- 
- README.md
- 
Thanks!
=> Extended Algorithm README.md

Pancake_Sort/Pancake_Sort.dart
Fixes #2151 
- Pancake sort is implemented in Dart
- Dart
- Pancake_Sort.dart
Thanks!
=> Pancake sort implemented in Dart - #2151 resolved

Cocktail_Sort/Cocktail_Sort.dart
Fixes #2144
- Cocktail sort is implemented in Dart
- Dart
- Cocktail_Sort.dart
Thanks!
=> Cocktail sort implemented in Dart - #2144 resolved

AKS_Primarility_Test/AKS.dart
Fixes #2111 
- AKS primality test is implemented in Dart
- Dart
- AKS.dart
Thanks!
=> Primality test implemented in Dart - #2111 resolved

Quick_Sort/Quick_Sort.ts
Fixes #2131 
- Added quicksort implementation in TypeScript
- TypeScript
- Quick_Sort.ts
- 
Thanks!
=> Created Quick_Sort.ts

AVL_Tree/avl_tree.php
Fixes #2112 
- Added AVL Tree implementation in PHP
- 
- PHP
- 
- avl_tree.php
- 
Thanks!
=> Added implementation of AVL tree in PHP

Floyd_Warshall_Algorithm/Floyd_Warshall_Algorithm.dart
Fixes #2205 
- 
- 
- Dart
- Floyd_Warshall_Algorithm.dart
Thanks!
=> Floyd Warshall Algorithm implemented in Dart
